export type OnlineSchoolTaster = {
  id: string;
  title: string;
  niche: string;
  audience: string;
  value: string;
  prompt: string;
  tags: string[];
};

const foundation = (focus: string, audience: string, delivery: string, outcome: string) => `Set up a ${delivery} online learning programme for ${audience} focused on ${focus}. Create a concise private programme foundation with practical, non-graded modules, human-reviewed milestones, and usable internal facilitator materials. Include an AI tutor configuration brief with a human escalation route and a private launch checklist. The learner-facing value should focus on ${outcome}. Prepare a configuration-readiness test only. Do not publish anything, create people, charge or collect money, create invoices, send messages, make outcome claims, issue credentials, or create a tutor account.`;

export const onlineSchoolTasters: OnlineSchoolTaster[] = [
  { id: "digital-literacy", title: "Digital literacy for adult beginners", niche: "Digital skills", audience: "adult beginners using phones or computers for everyday work", value: "A practical first-step programme for confident everyday digital participation.", prompt: foundation("everyday device use, organised files, email basics, and responsible online habits", "adult beginners using phones or computers for everyday work", "self-paced", "practical digital confidence"), tags: ["adult learning", "self-paced", "foundations"] },
  { id: "social-content", title: "Social media content planning", niche: "Digital skills", audience: "small-business owners and aspiring content assistants", value: "A repeatable internal course foundation for content planning and responsible publishing workflows.", prompt: foundation("content goals, audience-aware ideas, simple content calendars, and review routines", "small-business owners and aspiring content assistants", "blended", "a consistent content-planning routine"), tags: ["business", "content", "blended"] },
  { id: "canva-design", title: "Practical visual design with Canva", niche: "Creative skills", audience: "beginners creating simple visual communication assets", value: "A hands-on design taster with practice material outlines and human review checkpoints.", prompt: foundation("layout basics, brand-consistent visual choices, accessible text, and practice design briefs using Canva", "beginners creating simple visual communication assets", "self-paced", "clear, reviewable visual communication"), tags: ["design", "creator", "self-paced"] },
  { id: "excel-records", title: "Excel for small-business records", niche: "Business operations", audience: "small-business operators and operations assistants", value: "A practical spreadsheet-learning foundation without creating real finance records or advice.", prompt: foundation("spreadsheet structure, simple formulas, sorting, filtering, and reviewable practice tables", "small-business operators and operations assistants", "live online", "organised operational record practice"), tags: ["excel", "operations", "live online"] },
  { id: "sales-service", title: "Sales and customer-care foundations", niche: "Business operations", audience: "frontline sales and customer-service beginners", value: "A guided learning offer for respectful customer conversations and internal service routines.", prompt: foundation("customer needs discovery, respectful communication, product knowledge preparation, and follow-up routines", "frontline sales and customer-service beginners", "blended", "consistent customer-service practice"), tags: ["sales", "service", "blended"] },
  { id: "home-baking", title: "Home baking foundations", niche: "Practical trades", audience: "aspiring home bakers and food-business starters", value: "A private practical-course foundation with facilitators’ materials and review checkpoints.", prompt: foundation("ingredient planning, basic baking workflow, presentation practice, and internal quality-review routines", "aspiring home bakers and food-business starters", "blended", "a structured baking-practice routine"), tags: ["food", "practical", "blended"] },
  { id: "fashion-sewing", title: "Fashion sewing foundations", niche: "Practical trades", audience: "new fashion and sewing learners", value: "A starter learning blueprint for structured practice and human-supported craft development.", prompt: foundation("measuring, pattern awareness, machine-use orientation, stitch practice, and project reflection", "new fashion and sewing learners", "blended", "steady sewing-practice progress"), tags: ["fashion", "craft", "blended"] },
  { id: "salon-basics", title: "Salon service foundations", niche: "Practical trades", audience: "entry-level salon-service learners", value: "A human-reviewed foundation for salon routines and professional client-care practice.", prompt: foundation("client consultation routines, service preparation, salon organisation, and reflective practice", "entry-level salon-service learners", "blended", "a structured salon-service learning routine"), tags: ["beauty", "service", "practical"] },
  { id: "makeup-creative", title: "Creative makeup foundations", niche: "Creative skills", audience: "beginners exploring makeup artistry", value: "An internal creative-skills course starter with practice briefs and facilitator guidance.", prompt: foundation("creative looks, colour awareness, portfolio-style practice briefs, and human feedback routines", "beginners exploring makeup artistry", "blended", "a deliberate creative-practice portfolio"), tags: ["beauty", "creative", "portfolio"] },
  { id: "catering-operations", title: "Catering operations foundations", niche: "Practical trades", audience: "aspiring catering assistants and small-event food teams", value: "A practical operational learning foundation with role-play activities and review prompts.", prompt: foundation("menu planning routines, service sequencing, team coordination, and event-preparation checklists", "aspiring catering assistants and small-event food teams", "blended", "organised catering-operation practice"), tags: ["food", "operations", "teamwork"] },
  { id: "mobile-photography", title: "Mobile photography storytelling", niche: "Creative skills", audience: "new creators using mobile devices", value: "A creator-focused taster for purposeful visual storytelling and reviewable project work.", prompt: foundation("composition, light awareness, story sequencing, ethical image choices, and mobile-photo project briefs", "new creators using mobile devices", "self-paced", "purposeful visual storytelling practice"), tags: ["photography", "mobile", "creator"] },
  { id: "video-editing", title: "Short-form video editing", niche: "Creative skills", audience: "beginner creators and content assistants", value: "A project-based outline for editing practice, workflow discipline, and human review.", prompt: foundation("clip selection, simple editing structure, captions, export workflow, and draft-video reflection", "beginner creators and content assistants", "self-paced", "a repeatable editing-practice workflow"), tags: ["video", "creator", "self-paced"] },
  { id: "coding-young", title: "Coding foundations for young beginners", niche: "STEM learning", audience: "young beginners with adult learning supervision", value: "An age-aware internal coding foundation with non-graded practice prompts and escalation guidance.", prompt: foundation("computational thinking, simple coding patterns, small creative projects, and reflective practice", "young beginners with adult learning supervision", "blended", "curious, supported coding practice"), tags: ["coding", "young learners", "STEM"] },
  { id: "data-foundations", title: "Data analysis foundations", niche: "Digital skills", audience: "career explorers and operational staff", value: "A structured introduction to data-thinking and practical non-graded analysis activities.", prompt: foundation("questions, tidy data concepts, basic spreadsheet analysis, visual interpretation, and project reflection", "career explorers and operational staff", "live online", "clear data-analysis practice"), tags: ["data", "analytics", "career"] },
  { id: "project-management", title: "Project coordination foundations", niche: "Business operations", audience: "new project coordinators and team leads", value: "A practical internal learning offer for planning, communication, and retrospective routines.", prompt: foundation("project goals, task breakdown, simple timelines, stakeholder updates, and retrospective practice", "new project coordinators and team leads", "live online", "more organised project coordination"), tags: ["project", "leadership", "operations"] },
  { id: "product-discovery", title: "Product discovery foundations", niche: "Business operations", audience: "aspiring product and service builders", value: "A discovery-focused course foundation for problem framing and human-reviewed project briefs.", prompt: foundation("user-problem framing, assumptions, simple research plans, idea comparison, and project reflection", "aspiring product and service builders", "live online", "structured product-discovery practice"), tags: ["product", "innovation", "business"] },
  { id: "agribusiness-records", title: "Agribusiness record-keeping foundations", niche: "Enterprise skills", audience: "small-scale agriculture operators and assistants", value: "A practical learning outline for organised farm-operation records without creating real financial data.", prompt: foundation("farm activity logs, inventory awareness, seasonal planning, simple record templates, and human review routines", "small-scale agriculture operators and assistants", "blended", "organised agribusiness-operation records"), tags: ["agriculture", "enterprise", "records"] },
  { id: "solar-literacy", title: "Solar energy literacy", niche: "STEM learning", audience: "non-technical adults exploring solar-energy concepts", value: "A neutral, non-technical learning foundation for energy concepts and supervised discussion.", prompt: foundation("energy basics, solar-system concepts, responsible questions for professionals, and project discussion prompts", "non-technical adults exploring solar-energy concepts", "self-paced", "better-informed solar-energy conversations"), tags: ["energy", "STEM", "non-technical"] },
  { id: "study-skills", title: "Study skills and exam preparation habits", niche: "Academic support", audience: "secondary and tertiary learners with human supervision", value: "A learner-support foundation focused on planning and reflection, without performance guarantees.", prompt: foundation("study routines, time planning, active recall practice, reflection, and appropriate support-seeking", "secondary and tertiary learners with human supervision", "self-paced", "more intentional study habits"), tags: ["study", "academic", "self-paced"] },
];

if (onlineSchoolTasters.length !== 19) throw new Error("NSOS Taster Library must contain exactly 19 launch prompts.");
