import { trpc } from "@/lib/trpc";
import { ArrowUpRight, CheckCircle2, Loader2, School } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { useRoute } from "wouter";
import { originLgaLoadPresentation } from "@/lib/originPresentation";
import { useSessionDraft } from "@/hooks/useSessionDraft";
import { LocalDraftNotice } from "@/components/LocalDraftNotice";
import { BiodataPreviewDialog } from "@/components/BiodataPreviewDialog";
import { ClearFormConfirmation } from "@/components/ClearFormConfirmation";

const inputClass = "h-11 w-full rounded-xl border border-[#dfe5df] bg-[#fbfcfa] px-3 text-sm text-[#15201c] outline-none transition focus:border-[#0f5c4f] focus:ring-2 focus:ring-[#0f5c4f]/10";

const templateFieldMeta: Record<string, { label: string; type?: "date" | "textarea" | "select" | "originState" | "originLga" }> = {
  middleName: { label: "Applicant middle name" }, dateOfBirth: { label: "Date of birth", type: "date" }, placeOfBirth: { label: "Place of birth" }, nationality: { label: "Nationality" }, homeTown: { label: "Home town" }, stateOfOrigin: { label: "State of origin", type: "originState" }, localGovernmentOfOrigin: { label: "Local Government Area of origin", type: "originLga" }, gender: { label: "Gender", type: "select" }, residentialAddress: { label: "Residential address", type: "textarea" }, postalAddress: { label: "Postal address" }, priorSchool: { label: "Previous school" }, currentClass: { label: "Current class" }, religion: { label: "Religion" }, medicalHistory: { label: "Relevant medical history", type: "textarea" }, familyDoctor: { label: "Family doctor or clinic" }, guardianOccupation: { label: "Parent or guardian occupation" }, guardianOfficeAddress: { label: "Parent or guardian office address", type: "textarea" },
};

const fallbackTemplate = { admissionTitle: "School admission form", headerTagline: "NSOS online admissions", headerLogoUrl: null as string | null, headerAddressLine: null as string | null, headerContactLine: null as string | null, admissionFields: ["dateOfBirth", "stateOfOrigin", "localGovernmentOfOrigin", "gender", "priorSchool"], declarationText: "I confirm that the information provided is accurate to the best of my knowledge.", requireDeclaration: true };
const initialPublicAdmissionDraft = { form: { firstName: "", lastName: "", guardianName: "", guardianPhone: "", guardianEmail: "", notes: "" }, supplementalData: {} as Record<string, string>, declarationAccepted: false };

function PublicLetterhead({ schoolName, template }: { schoolName: string; template: { admissionTitle: string; headerTagline?: string | null; headerLogoUrl?: string | null; headerAddressLine?: string | null; headerContactLine?: string | null } }) {
  return <header className="bg-[#102a24] px-6 py-7 text-white sm:px-9"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-xl bg-[#dcefe1] text-[#123b31]">{template.headerLogoUrl ? <img src={template.headerLogoUrl} alt={`${schoolName} logo`} referrerPolicy="no-referrer" className="h-full w-full object-cover" onError={event => { event.currentTarget.style.display = "none"; }} /> : <School className="h-5 w-5" />}</span><div className="min-w-0"><p className="text-sm font-bold">{schoolName}</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-[.14em] text-white/55">{template.headerTagline || "NSOS online admissions"}</p>{template.headerAddressLine && <p className="mt-3 text-xs leading-5 text-white/70">{template.headerAddressLine}</p>}{template.headerContactLine && <p className="text-xs leading-5 text-white/70">{template.headerContactLine}</p>}</div></div><div className="mt-7 border-t border-white/15 pt-5"><h1 className="max-w-xl text-3xl font-semibold tracking-[-.045em]">{template.admissionTitle}</h1><p className="mt-2 text-sm leading-6 text-white/65">Complete the details below. Your information goes straight to the school’s secure admissions queue.</p></div></header>;
}

export default function PublicAdmissions() {
  const [, params] = useRoute("/apply/:shortCode");
  const shortCode = useMemo(() => params?.shortCode?.toUpperCase() ?? "", [params?.shortCode]);
  const school = trpc.nsos.admissions.publicSchool.useQuery({ shortCode }, { enabled: !!shortCode });
  const submit = trpc.nsos.admissions.publicSubmit.useMutation();
  const publicDraft = useSessionDraft({ storageKey: `nsos:public-admissions-draft:${shortCode || "unknown"}`, initialValue: initialPublicAdmissionDraft });
  const form = publicDraft.value.form;
  const supplementalData = publicDraft.value.supplementalData;
  const declarationAccepted = publicDraft.value.declarationAccepted;
  const setForm = (next: typeof form) => publicDraft.setValue(current => ({ ...current, form: next }));
  const setSupplementalData = (next: Record<string, string> | ((current: Record<string, string>) => Record<string, string>)) => publicDraft.setValue(current => ({ ...current, supplementalData: typeof next === "function" ? next(current.supplementalData) : next }));
  const setDeclarationAccepted = (next: boolean) => publicDraft.setValue(current => ({ ...current, declarationAccepted: next }));
  const [applicationNo, setApplicationNo] = useState<number | null>(null);
  const origins = trpc.nsos.admissions.originOptions.useQuery({ state: supplementalData.stateOfOrigin || undefined });
  const lgaStatus = originLgaLoadPresentation({ stateOfOrigin: supplementalData.stateOfOrigin, isLoading: origins.isLoading, isError: origins.isError });

  if (school.isLoading) return <main className="grid min-h-screen place-items-center bg-[#f5f6f1]"><Loader2 className="h-6 w-6 animate-spin text-[#0f5c4f]" /></main>;
  if (!school.data) return <main className="grid min-h-screen place-items-center bg-[#f5f6f1] p-5"><section className="max-w-md rounded-3xl border border-[#e0e5df] bg-white p-8 text-center shadow-sm"><School className="mx-auto h-7 w-7 text-[#0f5c4f]" /><h1 className="mt-4 text-xl font-semibold text-[#20342c]">Admissions link unavailable</h1><p className="mt-2 text-sm leading-6 text-[#758079]">Please return to your school’s official NSOS admissions link or contact the school office.</p></section></main>;
  if (applicationNo) return <main className="grid min-h-screen place-items-center bg-[#f5f6f1] p-5"><section className="max-w-lg rounded-[1.5rem] border border-[#e0e5df] bg-white p-8 text-center shadow-[0_16px_40px_rgba(16,45,35,0.06)]"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#e2f1e8] text-[#176145]"><CheckCircle2 className="h-6 w-6" /></span><p className="mt-5 text-xs font-semibold uppercase tracking-[.14em] text-[#0f5c4f]">Application received</p><h1 className="mt-2 text-2xl font-semibold tracking-[-.04em] text-[#20342c]">Thank you for applying to {school.data.name}.</h1><p className="mt-3 text-sm leading-6 text-[#758079]">Your application has entered the admissions review queue. The school will contact the guardian details provided with the next steps.</p><p className="mono mt-5 rounded-xl bg-[#f1f4f0] p-3 text-xs text-[#486057]">Reference: NSOS-APP-{applicationNo}</p></section></main>;

  const template = school.data.admissionTemplate ?? fallbackTemplate;
  const configuredFields = template.admissionFields.filter(field => templateFieldMeta[field]);
  const previewFields = [{ label: "Applicant first name", value: form.firstName }, { label: "Applicant last name", value: form.lastName }, { label: "Parent or guardian name", value: form.guardianName }, { label: "Parent or guardian phone", value: form.guardianPhone }, { label: "Parent or guardian email", value: form.guardianEmail }, ...configuredFields.map(field => ({ label: templateFieldMeta[field].label, value: supplementalData[field] })), { label: "Admissions note", value: form.notes }, ...(declarationAccepted ? [{ label: "Guardian declaration", value: "Confirmed" }] : [])];
  const updateSupplement = (field: string, value: string) => setSupplementalData(current => ({ ...current, [field]: value }));
  const renderConfiguredField = (field: string) => {
    const meta = templateFieldMeta[field];
    if (meta.type === "originState") return <Field key={field} label={meta.label}><select className={inputClass} value={supplementalData[field] ?? ""} onChange={event => setSupplementalData(current => ({ ...current, stateOfOrigin: event.target.value, localGovernmentOfOrigin: "" }))}><option value="">Select state of origin</option>{origins.data?.states.map(state => <option key={state} value={state}>{state}</option>)}</select></Field>;
    if (meta.type === "originLga") return <div key={field} className="grid gap-1.5"><Field label={meta.label}><select aria-describedby="public-origin-lga-status" aria-invalid={lgaStatus.state === "error" || undefined} disabled={!supplementalData.stateOfOrigin || lgaStatus.state === "loading" || lgaStatus.state === "error"} className={inputClass} value={supplementalData[field] ?? ""} onChange={event => updateSupplement(field, event.target.value)}><option value="">{lgaStatus.selectPlaceholder}</option>{origins.data?.lgas.map(lga => <option key={lga} value={lga}>{lga}</option>)}</select></Field>{lgaStatus.state === "loading" && <p id="public-origin-lga-status" role="status" aria-live="polite" className="flex items-center gap-1.5 text-[11px] font-medium text-[#55736a]"><Loader2 className="h-3.5 w-3.5 animate-spin" />{lgaStatus.message}</p>}{lgaStatus.state === "error" && <div id="public-origin-lga-status" role="alert" className="rounded-lg border border-[#f0c9c4] bg-[#fff7f5] px-3 py-2 text-[11px] leading-5 text-[#8f3b35]"><p>{lgaStatus.message}</p><button type="button" onClick={() => origins.refetch()} className="mt-1 font-bold text-[#9f352e] underline underline-offset-2">Retry loading LGAs</button></div>}</div>;
    if (meta.type === "select") return <Field key={field} label={meta.label}><select className={inputClass} value={supplementalData[field] ?? ""} onChange={event => updateSupplement(field, event.target.value)}><option value="">Prefer not to say</option><option value="female">Female</option><option value="male">Male</option><option value="other">Other</option><option value="prefer_not_to_say">Prefer not to say</option></select></Field>;
    if (meta.type === "textarea") return <Field key={field} label={meta.label}><textarea className={`${inputClass} min-h-24 h-auto py-3`} value={supplementalData[field] ?? ""} onChange={event => updateSupplement(field, event.target.value)} /></Field>;
    return <Field key={field} label={meta.label}><input type={meta.type ?? "text"} className={inputClass} value={supplementalData[field] ?? ""} onChange={event => updateSupplement(field, event.target.value)} /></Field>;
  };

  const submitApplication = (event: FormEvent) => {
    event.preventDefault();
    submit.mutate({ shortCode, ...form, guardianEmail: form.guardianEmail || undefined, priorSchool: supplementalData.priorSchool || undefined, dateOfBirth: supplementalData.dateOfBirth || undefined, gender: supplementalData.gender as "female" | "male" | "other" | "prefer_not_to_say" | undefined, notes: form.notes || undefined, supplementalData, declarationAccepted }, { onSuccess: result => { publicDraft.clearDraft(); setApplicationNo(result.applicationId); } });
  };

  return <main className="min-h-screen bg-[#f5f6f1] px-5 py-7 sm:p-10"><div className="mx-auto max-w-3xl overflow-hidden rounded-[1.6rem] border border-[#dfe5df] bg-white shadow-[0_20px_60px_rgba(19,53,42,0.08)]"><PublicLetterhead schoolName={school.data.name} template={template} /><form onSubmit={submitApplication} className="p-6 sm:p-9">{publicDraft.restored && <LocalDraftNotice onClear={publicDraft.clearDraft} />}<div className="grid gap-5 sm:grid-cols-2"><Field label="Applicant first name"><input required className={inputClass} value={form.firstName} onChange={event => setForm({ ...form, firstName: event.target.value })} /></Field><Field label="Applicant last name"><input required className={inputClass} value={form.lastName} onChange={event => setForm({ ...form, lastName: event.target.value })} /></Field><Field label="Parent or guardian name"><input required className={inputClass} value={form.guardianName} onChange={event => setForm({ ...form, guardianName: event.target.value })} /></Field><Field label="Parent or guardian phone"><input required className={inputClass} value={form.guardianPhone} onChange={event => setForm({ ...form, guardianPhone: event.target.value })} /></Field><Field label="Parent or guardian email"><input type="email" className={inputClass} value={form.guardianEmail} onChange={event => setForm({ ...form, guardianEmail: event.target.value })} /></Field>{configuredFields.map(renderConfiguredField)}</div><Field label="Anything the admissions team should know"><textarea className={`${inputClass} mt-1 h-24 py-3`} value={form.notes} onChange={event => setForm({ ...form, notes: event.target.value })} /></Field>{template.requireDeclaration && <label className="mt-5 flex gap-3 rounded-xl border border-[#e1e7df] bg-[#f7faf6] p-4 text-xs leading-5 text-[#526259]"><input required type="checkbox" checked={declarationAccepted} onChange={event => setDeclarationAccepted(event.target.checked)} className="mt-0.5 h-4 w-4 accent-[#0f5c4f]" /><span>{template.declarationText}</span></label>}{submit.error && <p className="mt-4 text-sm text-[#a13e38]">{submit.error.message}</p>}<div className="mt-6 flex flex-wrap gap-3"><ClearFormConfirmation onConfirm={publicDraft.clearDraft} /><BiodataPreviewDialog title={`${school.data.name} ${template.admissionTitle}`} subtitle="Pre-submission admissions biodata preview" fields={previewFields} /><button disabled={submit.isPending} className="inline-flex items-center gap-2 rounded-xl bg-[#0f5c4f] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{submit.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : null}Submit application <ArrowUpRight className="h-4 w-4" /></button></div></form></div></main>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>{label}</span>{children}</label>; }
