import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowUpRight, CheckCircle2, Loader2, School } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { Link, useRoute } from "wouter";

const inputClass = "h-11 w-full rounded-xl border border-[#dfe5df] bg-[#fbfcfa] px-3 text-sm text-[#15201c] outline-none transition focus:border-[#0f5c4f] focus:ring-2 focus:ring-[#0f5c4f]/10";

export default function PublicAdmissions() {
  const [, params] = useRoute("/apply/:shortCode");
  const shortCode = useMemo(() => params?.shortCode?.toUpperCase() ?? "", [params?.shortCode]);
  const school = trpc.nsos.admissions.publicSchool.useQuery({ shortCode }, { enabled: !!shortCode });
  const submit = trpc.nsos.admissions.publicSubmit.useMutation();
  const [form, setForm] = useState({ firstName: "", lastName: "", guardianName: "", guardianPhone: "", guardianEmail: "", priorSchool: "", notes: "" });
  const [applicationNo, setApplicationNo] = useState<number | null>(null);
  if (school.isLoading) return <main className="grid min-h-screen place-items-center bg-[#f5f6f1]"><Loader2 className="h-6 w-6 animate-spin text-[#0f5c4f]" /></main>;
  if (!school.data) return <main className="grid min-h-screen place-items-center bg-[#f5f6f1] p-5"><section className="max-w-md rounded-3xl border border-[#e0e5df] bg-white p-8 text-center shadow-sm"><School className="mx-auto h-7 w-7 text-[#0f5c4f]" /><h1 className="mt-4 text-xl font-semibold text-[#20342c]">Admissions link unavailable</h1><p className="mt-2 text-sm leading-6 text-[#758079]">Please return to your school’s official NSOS admissions link or contact the school office.</p></section></main>;
  if (applicationNo) return <main className="grid min-h-screen place-items-center bg-[#f5f6f1] p-5"><section className="max-w-lg rounded-[1.5rem] border border-[#e0e5df] bg-white p-8 text-center shadow-[0_16px_40px_rgba(16,45,35,0.06)]"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#e2f1e8] text-[#176145]"><CheckCircle2 className="h-6 w-6" /></span><p className="mt-5 text-xs font-semibold uppercase tracking-[.14em] text-[#0f5c4f]">Application received</p><h1 className="mt-2 text-2xl font-semibold tracking-[-.04em] text-[#20342c]">Thank you for applying to {school.data.name}.</h1><p className="mt-3 text-sm leading-6 text-[#758079]">Your application has entered the admissions review queue. The school will contact the guardian details provided with the next steps.</p><p className="mono mt-5 rounded-xl bg-[#f1f4f0] p-3 text-xs text-[#486057]">Reference: NSOS-APP-{applicationNo}</p></section></main>;
  return <main className="min-h-screen bg-[#f5f6f1] px-5 py-7 sm:p-10"><div className="mx-auto max-w-3xl overflow-hidden rounded-[1.6rem] border border-[#dfe5df] bg-white shadow-[0_20px_60px_rgba(19,53,42,0.08)]"><header className="bg-[#102a24] px-6 py-7 text-white sm:px-9"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#dcefe1] text-[#123b31]"><School className="h-4 w-4" /></span><div><p className="text-sm font-bold">{school.data.name}</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-[.14em] text-white/50">NSOS online admissions</p></div></div><h1 className="mt-8 max-w-xl text-3xl font-semibold tracking-[-.045em]">Begin your child’s application.</h1><p className="mt-2 text-sm leading-6 text-white/65">Complete the details below. Your information goes straight to the school’s secure admissions queue.</p></header><form onSubmit={(event: FormEvent) => { event.preventDefault(); submit.mutate({ shortCode, ...form, guardianEmail: form.guardianEmail || undefined, priorSchool: form.priorSchool || undefined, notes: form.notes || undefined }, { onSuccess: result => setApplicationNo(result.applicationId) }); }} className="p-6 sm:p-9"><div className="grid gap-5 sm:grid-cols-2"><Field label="Applicant first name"><input required className={inputClass} value={form.firstName} onChange={e => setForm({ ...form, firstName: e.target.value })} /></Field><Field label="Applicant last name"><input required className={inputClass} value={form.lastName} onChange={e => setForm({ ...form, lastName: e.target.value })} /></Field><Field label="Parent or guardian name"><input required className={inputClass} value={form.guardianName} onChange={e => setForm({ ...form, guardianName: e.target.value })} /></Field><Field label="Parent or guardian phone"><input required className={inputClass} value={form.guardianPhone} onChange={e => setForm({ ...form, guardianPhone: e.target.value })} /></Field><Field label="Parent or guardian email"><input type="email" className={inputClass} value={form.guardianEmail} onChange={e => setForm({ ...form, guardianEmail: e.target.value })} /></Field><Field label="Previous school"><input className={inputClass} value={form.priorSchool} onChange={e => setForm({ ...form, priorSchool: e.target.value })} /></Field></div><Field label="Anything the admissions team should know"><textarea className={`${inputClass} mt-1 h-24 py-3`} value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></Field>{submit.error && <p className="mt-4 text-sm text-[#a13e38]">{submit.error.message}</p>}<button disabled={submit.isPending} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#0f5c4f] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{submit.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : null}Submit application <ArrowUpRight className="h-4 w-4" /></button></form></div></main>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>{label}</span>{children}</label>; }
