import { trpc } from "@/lib/trpc";
import { BookOpenCheck, CheckCircle2, CircleAlert, Loader2, PauseCircle, PlayCircle, ShieldCheck, UserRoundCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const inputClass = "h-10 w-full rounded-lg border border-[#dfe5df] bg-[#fbfcfa] px-3 text-sm text-[#15201c] outline-none transition focus:border-[#0f5c4f] focus:ring-2 focus:ring-[#0f5c4f]/10";

export function AiTutorWorkspace({ schoolId }: { schoolId: number }) {
  const utils = trpc.useUtils();
  const workspace = trpc.nsos.aiTutors.workspace.useQuery({ schoolId });
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ subjectId: "", name: "", curriculumScope: "", allowedLevels: "All learners", supervisorUserId: "", dailyQuestionLimit: "20" });
  const refresh = () => utils.nsos.aiTutors.workspace.invalidate({ schoolId });
  const create = trpc.nsos.aiTutors.create.useMutation({ onSuccess: async () => { await refresh(); setShowForm(false); setForm({ subjectId: "", name: "", curriculumScope: "", allowedLevels: "All learners", supervisorUserId: "", dailyQuestionLimit: "20" }); toast.success("AI tutor saved as a draft. Review its scope and activate it only when supervision is ready."); }, onError: error => toast.error(error.message) });
  const setStatus = trpc.nsos.aiTutors.setStatus.useMutation({ onSuccess: async result => { await refresh(); toast.success(`Tutor ${result.status}.`); }, onError: error => toast.error(error.message) });
  if (workspace.isLoading) return <div className="grid min-h-[320px] place-items-center rounded-[1.2rem] border border-[#e0e5df] bg-white"><Loader2 className="h-5 w-5 animate-spin text-[#0f5c4f]" /></div>;
  if (workspace.error || !workspace.data) return <div className="rounded-[1.2rem] border border-[#ead1ce] bg-[#fff8f7] p-6"><p className="text-sm font-semibold text-[#903b34]">AI tutor workspace unavailable</p><p className="mt-1 text-xs leading-5 text-[#75524e]">{workspace.error?.message ?? "Try again shortly."}</p></div>;
  const { tutors, subjects, supervisors } = workspace.data;
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate({ schoolId, subjectId: Number(form.subjectId), name: form.name, curriculumScope: form.curriculumScope, allowedLevels: form.allowedLevels.split(",").map(value => value.trim()).filter(Boolean), supervisorUserId: Number(form.supervisorUserId), dailyQuestionLimit: Number(form.dailyQuestionLimit) }); };
  return <div className="grid gap-6"><section className="rounded-[1.2rem] bg-[#123b31] p-6 text-white sm:p-7"><div className="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-white/50">Supervised learning support</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.045em]">Subject help, under school control.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-white/65">AI tutors support approved subjects when teaching capacity is limited. Every tutor has a school-appointed supervisor, a narrow curriculum scope, a daily question limit, and a direct learner route to request human support.</p></div><div className="rounded-xl border border-white/10 bg-white/[.08] px-4 py-3 text-xs"><p className="font-semibold">Human accountability stays in place</p><p className="mt-1 text-white/60">No autonomous grading, discipline, safeguarding decision, or replacement for required staffing.</p></div></div></section>
    <section className="overflow-hidden rounded-[1.2rem] border border-[#e0e5df] bg-white shadow-[0_10px_32px_rgba(16,45,35,.035)]"><div className="flex flex-col gap-4 border-b border-[#e7ebe6] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><p className="text-sm font-semibold text-[#2d4439]">Tutor roles</p><p className="mt-1 text-xs leading-5 text-[#758079]">Configure one supervised tutor per subject. Start in draft; activation makes the tutor available only to eligible linked student accounts.</p></div><button type="button" onClick={() => setShowForm(current => !current)} className="inline-flex w-fit items-center gap-2 rounded-xl bg-[#123b31] px-4 py-2.5 text-xs font-bold text-white"><BookOpenCheck className="h-3.5 w-3.5" />{showForm ? "Close setup" : "Configure AI tutor"}</button></div>
      {showForm && <form onSubmit={submit} className="grid gap-4 border-b border-[#e7ebe6] bg-[#fbfcfa] p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><Field label="Approved subject"><select required className={inputClass} value={form.subjectId} onChange={event => setForm({ ...form, subjectId: event.target.value })}><option value="">Select subject</option>{subjects.map(subject => <option key={subject.id} value={subject.id}>{subject.name} · {subject.code}</option>)}</select></Field><Field label="Tutor display name"><input required className={inputClass} value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="Mathematics study guide" /></Field></div><Field label="Approved curriculum scope"><textarea required minLength={30} maxLength={3000} className={`${inputClass} h-28 py-2`} value={form.curriculumScope} onChange={event => setForm({ ...form, curriculumScope: event.target.value })} placeholder="State exactly what this tutor may explain, practise, and refer to a teacher. Do not include private learner records or sensitive content." /></Field><div className="grid gap-4 sm:grid-cols-3"><Field label="Allowed class levels"><input required className={inputClass} value={form.allowedLevels} onChange={event => setForm({ ...form, allowedLevels: event.target.value })} placeholder="All learners, JSS 1" /><span className="text-[11px] font-normal text-[#758079]">Use “All learners” or the exact class-level labels used by the school.</span></Field><Field label="Accountable supervisor"><select required className={inputClass} value={form.supervisorUserId} onChange={event => setForm({ ...form, supervisorUserId: event.target.value })}><option value="">Select staff supervisor</option>{supervisors.map(supervisor => <option key={supervisor.userId} value={supervisor.userId}>{supervisor.name || `User #${supervisor.userId}`} · {supervisor.role}</option>)}</select></Field><Field label="Daily learner question limit"><input required type="number" min="1" max="50" className={inputClass} value={form.dailyQuestionLimit} onChange={event => setForm({ ...form, dailyQuestionLimit: event.target.value })} /></Field></div><div className="flex flex-wrap items-center justify-between gap-3"><p className="max-w-2xl text-xs leading-5 text-[#758079]">Creating a tutor does not activate it. Learner conversations are not stored; only aggregate daily usage and support-request states are retained.</p><button disabled={create.isPending} className="rounded-xl bg-[#0f5c4f] px-5 py-2.5 text-sm font-bold text-white disabled:opacity-60">{create.isPending ? "Saving…" : "Save tutor draft"}</button></div></form>}
      {tutors.length ? <div>{tutors.map(tutor => { const helpfulnessRate = tutor.feedback.total ? Math.round((tutor.feedback.helpful / tutor.feedback.total) * 100) : 0; return <article key={tutor.id} className="flex flex-col gap-4 border-b border-[#edf0eb] p-5 last:border-0 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-[#30463b]">{tutor.name}</p><Status status={tutor.status} /></div><p className="mt-1 text-xs leading-5 text-[#68776f]">{tutor.subjectName} · {Array.isArray(tutor.allowedLevels) ? tutor.allowedLevels.join(", ") : "Approved levels"} · {tutor.dailyQuestionLimit} questions/day</p><p className="mt-1 text-xs text-[#758079]">Supervisor: {tutor.supervisorName} · {tutor.openEscalations} open support request{tutor.openEscalations === 1 ? "" : "s"}</p><div className="mt-2 flex flex-wrap items-center gap-2 text-[11px]"><span className="rounded-full bg-[#edf3ed] px-2.5 py-1 font-bold text-[#176145]">{tutor.feedback.total ? `${helpfulnessRate}% helpful` : "No ratings yet"}</span>{tutor.feedback.total ? <span className="text-[#758079]">{tutor.feedback.total} rating{tutor.feedback.total === 1 ? "" : "s"} · {tutor.feedback.partlyHelpful} partly helpful · {tutor.feedback.notHelpful} not helpful</span> : null}</div><p className="mt-2 max-w-2xl text-xs leading-5 text-[#65746c]">{tutor.curriculumScope}</p></div><div className="flex shrink-0 flex-wrap gap-2">{tutor.status !== "active" && tutor.status !== "retired" && <button type="button" disabled={setStatus.isPending} onClick={() => setStatus.mutate({ schoolId, tutorId: tutor.id, status: "active" })} className="inline-flex items-center gap-1.5 rounded-lg bg-[#176145] px-3 py-2 text-xs font-bold text-white"><PlayCircle className="h-3.5 w-3.5" />Activate</button>}{tutor.status === "active" && <button type="button" disabled={setStatus.isPending} onClick={() => setStatus.mutate({ schoolId, tutorId: tutor.id, status: "paused" })} className="inline-flex items-center gap-1.5 rounded-lg border border-[#d8c49e] bg-[#fffaf0] px-3 py-2 text-xs font-bold text-[#76521a]"><PauseCircle className="h-3.5 w-3.5" />Pause</button>}</div></article>; })}</div> : <div className="p-7 text-center"><UserRoundCheck className="mx-auto h-5 w-5 text-[#9aa7a0]" /><p className="mt-3 text-sm font-semibold text-[#44564d]">No AI tutors configured</p><p className="mx-auto mt-1 max-w-md text-xs leading-5 text-[#758079]">Create an approved subject tutor only after a responsible school supervisor and curriculum scope have been assigned.</p></div>}</section>
    <section className="rounded-[1.2rem] border border-[#d9e7dc] bg-[#f6fbf7] p-5"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-white text-[#176145]"><ShieldCheck className="h-4 w-4" /></span><div><p className="text-sm font-semibold text-[#29483b]">Safeguarding boundary</p><p className="mt-1 text-xs leading-5 text-[#65746c]">Tutors can explain approved study material and flag a request for human review. They cannot grade, discipline, make eligibility or welfare decisions, or replace a school’s safeguarding and staffing duties.</p></div></div></section></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>{label}</span>{children}</label>; }
function Status({ status }: { status: string }) { const active = status === "active"; return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.1em] ${active ? "bg-[#e2f1e8] text-[#176145]" : status === "paused" ? "bg-[#fff4dc] text-[#8a5a12]" : "bg-[#eef0ec] text-[#65736b]"}`}>{active ? <CheckCircle2 className="h-3.5 w-3.5" /> : <CircleAlert className="h-3.5 w-3.5" />}{status}</span>; }
