import { trpc } from "@/lib/trpc";
import { BookOpenCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const inputClass = "h-10 w-full rounded-lg border border-[#dfe5df] bg-[#fbfcfa] px-3 text-sm text-[#15201c] outline-none transition focus:border-[#0f5c4f] focus:ring-2 focus:ring-[#0f5c4f]/10";

export function CurriculumStation({ schoolId, academic, onDone }: { schoolId: number; academic: any; onDone: () => void }) {
  const [classSubjectId, setClassSubjectId] = useState(""); const [termId, setTermId] = useState(""); const [title, setTitle] = useState(""); const [targetWeek, setTargetWeek] = useState("1");
  const create = trpc.nsos.academics.createCurriculumMilestone.useMutation({ onSuccess: () => { toast.success("Curriculum milestone added."); setTitle(""); onDone(); }, onError: error => toast.error(error.message) });
  const className = new Map<number, string>((academic?.classes ?? []).map((item: any) => [Number(item.id), String(item.name)])); const subjectName = new Map<number, string>((academic?.subjects ?? []).map((item: any) => [Number(item.id), String(item.name)]));
  return <section className="rounded-[1.2rem] border border-[#e0e5df] bg-white p-5 shadow-[0_10px_32px_rgba(16,45,35,0.035)] sm:p-6"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf3ed] text-[#0f5c4f]"><BookOpenCheck className="h-4 w-4" /></span><div><p className="text-sm font-semibold text-[#2d4439]">Curriculum coverage</p><p className="mt-1 text-xs text-[#758079]">Set teaching milestones against a class-subject and term to keep coverage visible.</p></div></div><form onSubmit={(event: FormEvent) => { event.preventDefault(); create.mutate({ schoolId, classSubjectId: Number(classSubjectId), termId: termId ? Number(termId) : undefined, title, targetWeek: Number(targetWeek) }); }} className="mt-5 grid gap-3 sm:grid-cols-4"><label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>Class subject</span><select required className={inputClass} value={classSubjectId} onChange={event => setClassSubjectId(event.target.value)}><option value="">Select class subject</option>{(academic?.classSubjects ?? []).map((item: any) => <option value={item.id} key={item.id}>{className.get(item.classId) ?? `Class #${item.classId}`} · {subjectName.get(item.subjectId) ?? `Subject #${item.subjectId}`}</option>)}</select></label><label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>Term</span><select className={inputClass} value={termId} onChange={event => setTermId(event.target.value)}><option value="">All session</option>{(academic?.terms ?? []).map((item: any) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>Target week</span><input required type="number" min="1" max="20" className={inputClass} value={targetWeek} onChange={event => setTargetWeek(event.target.value)} /></label><label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>Milestone</span><input required className={inputClass} value={title} onChange={event => setTitle(event.target.value)} placeholder="Topic completion" /></label><button className="sm:col-span-4 w-fit rounded-xl bg-[#0f5c4f] px-4 py-2.5 text-sm font-bold text-white">Add coverage milestone</button></form>{academic?.curriculum?.length ? <div className="mt-5 divide-y divide-[#edf0eb] border-t border-[#edf0eb]">{academic.curriculum.slice(0, 6).map((item: any) => <div key={item.id} className="flex items-center justify-between gap-3 py-3"><span className="text-xs font-semibold text-[#31463c]">{item.title}</span><span className="rounded-full bg-[#edf3ed] px-2.5 py-1 text-[10px] font-semibold text-[#0f5c4f]">Week {item.targetWeek ?? "—"}</span></div>)}</div> : null}</section>;
}
