import { Moon, Sun } from "lucide-react";
import { useTheme } from "@/contexts/ThemeContext";

export function DashboardAppearanceSettings() {
  const { theme, toggleTheme, switchable } = useTheme();
  if (!switchable || !toggleTheme) return null;
  const isDark = theme === "dark";
  const action = isDark ? "Switch to light mode" : "Switch to dark mode";
  return <section id="dashboard-appearance-settings" className="dashboard-appearance-settings rounded-[1.25rem] border border-[#dce9e0] bg-white p-5 shadow-[0_10px_28px_rgba(25,58,42,.04)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${isDark ? "bg-[#223b31] text-[#a6e6bc]" : "bg-[#edf7f0] text-[#0f6a50]"}`}>{isDark ? <Moon className="h-5 w-5" aria-hidden="true" /> : <Sun className="h-5 w-5" aria-hidden="true" />}</span><div><p className="text-sm font-extrabold text-[#294d3d]">Dashboard appearance</p><p className="mt-1 max-w-xl text-xs leading-5 text-[#6d8276]">Choose the display that is most comfortable for your current environment. This preference is saved on this device and changes the NSOS interface only; it does not alter institution data, settings, or access.</p></div></div><button type="button" aria-label={action} aria-pressed={isDark} onClick={toggleTheme} className="inline-flex min-h-11 shrink-0 items-center justify-center gap-2 rounded-xl border border-[#b8d4c2] bg-[#f7fcf8] px-4 text-xs font-extrabold text-[#176147] transition hover:border-[#7fb492] hover:bg-[#edf8f0] active:scale-[.98] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#0f6a50] focus-visible:ring-offset-2 dark:border-[#527164] dark:bg-[#17241e] dark:text-[#c9f3d6] dark:hover:bg-[#23352d] dark:focus-visible:ring-[#9bdcaf] dark:focus-visible:ring-offset-[#0d1512]">{isDark ? <Sun className="h-4 w-4" aria-hidden="true" /> : <Moon className="h-4 w-4" aria-hidden="true" />}<span>{isDark ? "Use light mode" : "Use dark mode"}</span></button></div><div className="mt-4 flex items-center gap-2 rounded-lg border border-[#e2ece5] bg-[#fbfdfb] px-3 py-2 text-[10px] leading-4 text-[#6e8177] dark:border-[#3d5147] dark:bg-[#17241e] dark:text-[#b8c8bf]"><span className={`h-2 w-2 rounded-full ${isDark ? "bg-[#8ed5a5]" : "bg-[#0f6a50]"}`} aria-hidden="true" />Current setting: <strong className="text-[#315746] dark:text-[#d5eadb]">{isDark ? "Dark mode" : "Light mode"}</strong></div></section>;
}
