import { trpc } from "@/lib/trpc";
import { BadgeCheck, BookMarked, ClipboardCheck, FileCheck2, LockKeyhole, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { curatedLearningSources } from "@shared/curatedLearningSources";

const inputClass = "h-10 w-full rounded-lg border border-[#dfe5df] bg-[#fbfcfa] px-3 text-sm text-[#15201c] outline-none transition focus:border-[#0f5c4f] focus:ring-2 focus:ring-[#0f5c4f]/10";

export function LearningDesignGovernance({ schoolId, data, onChanged }: { schoolId: number; data: any; onChanged: () => Promise<void> }) {
  const utils = trpc.useUtils();
  const [source, setSource] = useState({ title: "", organisation: "", sourceUrl: "", category: "institution_approved" as "institution_approved" | "professional_body" | "learning_resource", allowedUse: "", confirmed: false });
  const [policy, setPolicy] = useState({ programId: "", issuerName: "", credentialTitle: "", completionCriteria: "", confirmed: false });
  const [activation, setActivation] = useState({ policyId: "", confirmed: false });
  const [issuance, setIssuance] = useState({ policyId: "", enrollmentId: "", evidenceSummary: "", confirmed: false });
  const createSource = trpc.nsos.learningOperations.createEvidenceSource.useMutation({ onSuccess: async () => { toast.success("Institution-approved source saved for controlled planning use."); setSource({ title: "", organisation: "", sourceUrl: "", category: "institution_approved", allowedUse: "", confirmed: false }); await utils.nsos.learningOperations.evidenceSources.invalidate({ schoolId }); await onChanged(); }, onError: error => toast.error(error.message) });
  const createPolicy = trpc.nsos.learningOperations.createCertificationPolicy.useMutation({ onSuccess: async () => { toast.success("Certification policy saved as a private draft. Activate it separately after review."); setPolicy({ programId: "", issuerName: "", credentialTitle: "", completionCriteria: "", confirmed: false }); await onChanged(); }, onError: error => toast.error(error.message) });
  const activatePolicy = trpc.nsos.learningOperations.activateCertificationPolicy.useMutation({ onSuccess: async () => { toast.success("Certification policy activated for controlled private issuance."); setActivation({ policyId: "", confirmed: false }); await onChanged(); }, onError: error => toast.error(error.message) });
  const issueCertificate = trpc.nsos.learningOperations.issuePrivateCertificate.useMutation({ onSuccess: async result => { toast.success(`Private issuer record ${result.certificateReference} created. No public verification was enabled.`); setIssuance({ policyId: "", enrollmentId: "", evidenceSummary: "", confirmed: false }); await onChanged(); }, onError: error => toast.error(error.message) });
  const activePrograms = useMemo(() => (data.programs ?? []).filter((item: any) => item.status === "active"), [data.programs]);
  const completedEnrolments = useMemo(() => (data.enrolments ?? []).filter((item: any) => item.status === "completed"), [data.enrolments]);
  const activePolicies = useMemo(() => (data.certificationPolicies ?? []).filter((item: any) => item.status === "active"), [data.certificationPolicies]);

  return <section className="rounded-[1.2rem] border border-[#d9e7dc] bg-white p-5 shadow-[0_10px_32px_rgba(16,45,35,.035)] sm:p-6">
    <div className="flex flex-col gap-4 border-b border-[#e1ebe3] pb-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edf7ef] text-[#176145]"><BookMarked className="h-5 w-5" /></span><div><p className="text-sm font-bold text-[#2d4439]">Evidence, experience and certification controls</p><p className="mt-1 max-w-3xl text-xs leading-5 text-[#64796d]">Use curated planning references, tailor learning delivery, and make institution-controlled private issuer records only after human completion review.</p></div></div><span className="w-fit rounded-full bg-[#fff7e7] px-3 py-1.5 text-[9px] font-extrabold uppercase tracking-[.1em] text-[#87601d]">No accreditation or public verification</span></div>
    <div className="mt-5 grid gap-6 xl:grid-cols-2">
      <div className="rounded-xl border border-[#dce9df] bg-[#fbfdfb] p-4"><div className="flex gap-2"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#176145]" /><div><p className="text-xs font-bold text-[#315141]">Curated reference library</p><p className="mt-1 text-[10px] leading-4 text-[#6a7f73]">These optional references are available in Course Studio. They guide planning only and never establish approval, alignment, accreditation, or certification.</p></div></div><div className="mt-3 grid gap-2">{curatedLearningSources.map(item => <a key={item.id} href={item.sourceUrl} target="_blank" rel="noreferrer" className="rounded-lg border border-[#e0ebe3] bg-white p-2.5 transition hover:border-[#a8d6b7]"><p className="text-[11px] font-bold text-[#2e5644]">{item.title}</p><p className="mt-0.5 text-[10px] text-[#668071]">{item.organisation} · {item.allowedUse}</p></a>)}</div>{data.evidenceSources?.length ? <div className="mt-4"><p className="text-[10px] font-bold uppercase tracking-[.08em] text-[#60796c]">Institution-approved planning sources</p><div className="mt-2 grid gap-2">{data.evidenceSources.map((item: any) => <a key={item.id} href={item.sourceUrl} target="_blank" rel="noreferrer" className="rounded-lg border border-[#e0ebe3] bg-white p-2.5"><p className="text-[11px] font-bold text-[#2e5644]">{item.title}</p><p className="mt-0.5 text-[10px] text-[#668071]">{item.organisation} · {item.category.replaceAll("_", " ")} · {item.status}</p></a>)}</div></div> : null}</div>
      <div className="rounded-xl border border-[#dce9df] bg-[#fbfdfb] p-4"><div className="flex gap-2"><ClipboardCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#176145]" /><div><p className="text-xs font-bold text-[#315141]">Add an institution-approved planning source</p><p className="mt-1 text-[10px] leading-4 text-[#6a7f73]">Record a source your organisation may use for editable planning. Do not copy third-party content or label a source as an approval.</p></div></div><div className="mt-3 grid gap-2"><input value={source.title} onChange={event => setSource({ ...source, title: event.target.value })} className={inputClass} maxLength={180} placeholder="Source title" /><input value={source.organisation} onChange={event => setSource({ ...source, organisation: event.target.value })} className={inputClass} maxLength={180} placeholder="Organisation or publisher" /><input value={source.sourceUrl} onChange={event => setSource({ ...source, sourceUrl: event.target.value })} className={inputClass} maxLength={2048} placeholder="https://…" /><select value={source.category} onChange={event => setSource({ ...source, category: event.target.value as typeof source.category })} className={inputClass}><option value="institution_approved">Institution-approved</option><option value="professional_body">Professional body</option><option value="learning_resource">Learning resource</option></select><textarea value={source.allowedUse} onChange={event => setSource({ ...source, allowedUse: event.target.value })} maxLength={500} className="min-h-20 rounded-lg border border-[#dfe5df] bg-[#fbfcfa] px-3 py-2 text-sm text-[#15201c] outline-none focus:border-[#0f5c4f]" placeholder="State the limited planning use, e.g. ‘Use only as an editable reference for module sequencing.’" /></div><label className="mt-3 flex gap-2 text-[10px] font-semibold leading-4 text-[#675326]"><input type="checkbox" checked={source.confirmed} onChange={event => setSource({ ...source, confirmed: event.target.checked })} className="mt-0.5 h-4 w-4 accent-[#0f5c4f]" />I confirm this is an organisation-approved planning reference and is not being added as accreditation or course approval evidence.</label><button type="button" disabled={!source.confirmed || source.title.trim().length < 3 || source.organisation.trim().length < 2 || source.allowedUse.trim().length < 20 || !source.sourceUrl.trim() || createSource.isPending} onClick={() => createSource.mutate({ schoolId, title: source.title.trim(), organisation: source.organisation.trim(), sourceUrl: source.sourceUrl.trim(), category: source.category, allowedUse: source.allowedUse.trim(), confirmed: true })} className="mt-3 rounded-lg bg-[#0f5c4f] px-3.5 py-2 text-xs font-bold text-white disabled:opacity-50">{createSource.isPending ? "Saving…" : "Save planning source"}</button></div>
    </div>
    <div className="mt-6 rounded-xl border border-[#ead9ae] bg-[#fffaf0] p-4"><div className="flex gap-2"><LockKeyhole className="mt-0.5 h-4 w-4 shrink-0 text-[#87601d]" /><div><p className="text-xs font-bold text-[#705a2b]">NSOS-powered private certification</p><p className="mt-1 text-[10px] leading-4 text-[#7b6637]">This is an institution-issued private record, not an accredited or professionally recognised qualification. It has no public verification page, automatic award, PDF, message, payment, account, or tutor action.</p></div></div><div className="mt-4 grid gap-5 xl:grid-cols-3"><div><p className="text-[11px] font-bold text-[#705a2b]">1. Create a policy draft</p><div className="mt-2 grid gap-2"><select value={policy.programId} onChange={event => setPolicy({ ...policy, programId: event.target.value, confirmed: false })} className={inputClass}><option value="">Select active programme</option>{activePrograms.map((item: any) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><input value={policy.issuerName} onChange={event => setPolicy({ ...policy, issuerName: event.target.value })} className={inputClass} maxLength={180} placeholder="Institution issuer name" /><input value={policy.credentialTitle} onChange={event => setPolicy({ ...policy, credentialTitle: event.target.value })} className={inputClass} maxLength={180} placeholder="Private record title" /><textarea value={policy.completionCriteria} onChange={event => setPolicy({ ...policy, completionCriteria: event.target.value })} maxLength={1200} className="min-h-24 rounded-lg border border-[#dfe5df] bg-[#fbfcfa] px-3 py-2 text-sm text-[#15201c] outline-none focus:border-[#0f5c4f]" placeholder="State completion and human-review requirements." /></div><label className="mt-3 flex gap-2 text-[10px] font-semibold leading-4 text-[#675326]"><input type="checkbox" checked={policy.confirmed} onChange={event => setPolicy({ ...policy, confirmed: event.target.checked })} className="mt-0.5 h-4 w-4 accent-[#0f5c4f]" />I confirm this is a private institution policy, not an accreditation claim.</label><button type="button" disabled={!policy.confirmed || !policy.programId || policy.issuerName.trim().length < 2 || policy.credentialTitle.trim().length < 3 || policy.completionCriteria.trim().length < 30 || createPolicy.isPending} onClick={() => createPolicy.mutate({ schoolId, programId: Number(policy.programId), issuerName: policy.issuerName.trim(), credentialTitle: policy.credentialTitle.trim(), completionCriteria: policy.completionCriteria.trim(), confirmed: true })} className="mt-3 rounded-lg bg-[#8a6116] px-3.5 py-2 text-xs font-bold text-white disabled:opacity-50">{createPolicy.isPending ? "Saving…" : "Create policy draft"}</button></div>
      <div><p className="text-[11px] font-bold text-[#705a2b]">2. Activate after a separate review</p><select value={activation.policyId} onChange={event => setActivation({ policyId: event.target.value, confirmed: false })} className={`${inputClass} mt-2`}><option value="">Select draft policy</option>{(data.certificationPolicies ?? []).filter((item: any) => item.status === "draft").map((item: any) => <option key={item.id} value={item.id}>{item.credentialTitle} · {item.programTitle}</option>)}</select><label className="mt-3 flex gap-2 text-[10px] font-semibold leading-4 text-[#675326]"><input type="checkbox" checked={activation.confirmed} onChange={event => setActivation({ ...activation, confirmed: event.target.checked })} className="mt-0.5 h-4 w-4 accent-[#0f5c4f]" />I separately approve activation of this private issuer policy.</label><button type="button" disabled={!activation.confirmed || !activation.policyId || activatePolicy.isPending} onClick={() => activatePolicy.mutate({ schoolId, certificationPolicyId: Number(activation.policyId), confirmed: true })} className="mt-3 rounded-lg border border-[#b58b37] bg-white px-3.5 py-2 text-xs font-bold text-[#76500c] disabled:opacity-50">{activatePolicy.isPending ? "Activating…" : "Activate private policy"}</button><div className="mt-5 border-t border-[#ead9ae] pt-4"><p className="text-[10px] font-bold uppercase tracking-[.08em] text-[#705a2b]">Policy register</p><div className="mt-2 grid gap-2">{(data.certificationPolicies ?? []).length ? data.certificationPolicies.map((item: any) => <div key={item.id} className="rounded-lg border border-[#eadfbe] bg-white/70 p-2.5"><p className="text-[11px] font-bold text-[#624d22]">{item.credentialTitle}</p><p className="mt-0.5 text-[10px] text-[#806d42]">{item.programTitle} · {item.status} · private only</p></div>) : <p className="text-[10px] text-[#806d42]">No private issuer policy exists yet.</p>}</div></div></div>
      <div><p className="text-[11px] font-bold text-[#705a2b]">3. Issue only after evidence review</p><p className="mt-1 text-[10px] leading-4 text-[#806d42]">The server requires an active policy, human-confirmed completed enrolment in the same programme, all active milestones reviewed complete, and this evidence summary.</p><div className="mt-2 grid gap-2"><select value={issuance.policyId} onChange={event => setIssuance({ ...issuance, policyId: event.target.value, confirmed: false })} className={inputClass}><option value="">Select active policy</option>{activePolicies.map((item: any) => <option key={item.id} value={item.id}>{item.credentialTitle} · {item.programTitle}</option>)}</select><select value={issuance.enrollmentId} onChange={event => setIssuance({ ...issuance, enrollmentId: event.target.value, confirmed: false })} className={inputClass}><option value="">Select completed learner enrolment</option>{completedEnrolments.map((item: any) => <option key={item.id} value={item.id}>{item.learnerName} · {item.programTitle}</option>)}</select><textarea value={issuance.evidenceSummary} onChange={event => setIssuance({ ...issuance, evidenceSummary: event.target.value })} maxLength={1200} className="min-h-24 rounded-lg border border-[#dfe5df] bg-[#fbfcfa] px-3 py-2 text-sm text-[#15201c] outline-none focus:border-[#0f5c4f]" placeholder="Summarise the human-reviewed milestone and completion evidence." /></div><label className="mt-3 flex gap-2 text-[10px] font-semibold leading-4 text-[#675326]"><input type="checkbox" checked={issuance.confirmed} onChange={event => setIssuance({ ...issuance, confirmed: event.target.checked })} className="mt-0.5 h-4 w-4 accent-[#0f5c4f]" />I confirm the institution has reviewed the evidence and authorises this one private issuer record.</label><button type="button" disabled={!issuance.confirmed || !issuance.policyId || !issuance.enrollmentId || issuance.evidenceSummary.trim().length < 30 || issueCertificate.isPending} onClick={() => issueCertificate.mutate({ schoolId, certificationPolicyId: Number(issuance.policyId), enrollmentId: Number(issuance.enrollmentId), evidenceSummary: issuance.evidenceSummary.trim(), confirmed: true })} className="mt-3 rounded-lg bg-[#8a6116] px-3.5 py-2 text-xs font-bold text-white disabled:opacity-50">{issueCertificate.isPending ? "Issuing…" : "Issue private record"}</button></div></div></div>
    <div className="mt-5 border-t border-[#ead9ae] pt-4"><div className="flex items-center gap-2"><FileCheck2 className="h-4 w-4 text-[#87601d]" /><p className="text-xs font-bold text-[#705a2b]">Private issuer record register</p></div>{data.certificates?.length ? <div className="mt-3 grid gap-2 md:grid-cols-2">{data.certificates.map((item: any) => <article key={item.id} className="rounded-lg border border-[#eadfbe] bg-white/70 p-3"><div className="flex items-center justify-between gap-2"><p className="text-[11px] font-bold text-[#624d22]">{item.certificateReference}</p><BadgeCheck className="h-4 w-4 text-[#87601d]" /></div><p className="mt-1 text-[10px] text-[#806d42]">{item.learnerName} · {item.credentialTitle}</p><p className="mt-1 text-[10px] text-[#806d42]">Private institution record · Public verification disabled</p></article>)}</div> : <p className="mt-3 text-[10px] text-[#806d42]">No private issuer record has been issued.</p>}</div>
  </section>;
}
