import { trpc } from "@/lib/trpc";
import { BookOpenCheck, Building2, Check, Landmark, LockKeyhole, Plus, ShieldCheck } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";

const inputClass = "h-10 w-full rounded-lg border border-[#dfe5df] bg-[#fbfcfa] px-3 text-sm text-[#15201c] outline-none transition focus:border-[#0f5c4f] focus:ring-2 focus:ring-[#0f5c4f]/10";

export function NigerianCurriculumSetup({ schoolId, academic, canConfigure, onDone }: { schoolId: number; academic: any; canConfigure: boolean; onDone: () => void }) {
  const templates = trpc.nsos.academics.curriculumTemplates.useQuery({ schoolId });
  const [templateId, setTemplateId] = useState("");
  const [classIds, setClassIds] = useState<number[]>([]);
  const [includeOptional, setIncludeOptional] = useState(false);
  const selectedTemplate = useMemo(() => templates.data?.find(template => template.id === templateId), [templateId, templates.data]);
  const apply = trpc.nsos.academics.applyNigerianCurriculumTemplate.useMutation({
    onSuccess: result => { toast.success(`${result.template} applied to ${result.classIds.length} class${result.classIds.length === 1 ? "" : "es"}.`); setClassIds([]); onDone(); },
    onError: error => toast.error(error.message),
  });
  const toggleClass = (classId: number) => setClassIds(current => current.includes(classId) ? current.filter(id => id !== classId) : [...current, classId]);
  const profile = academic?.curriculumProfile;
  return <section className="rounded-[1.2rem] border border-[#d7e5da] bg-[#f8fcf8] p-5 shadow-[0_10px_32px_rgba(16,45,35,0.035)] sm:p-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#e2f1e8] text-[#0f5c4f]"><BookOpenCheck className="h-5 w-5" /></span><div><p className="text-sm font-semibold text-[#294238]">Nigerian curriculum & subject setup</p><p className="mt-1 max-w-2xl text-xs leading-5 text-[#64766b]">Start from an editable NERDC-aligned subject template, choose the classes it applies to, then review your school’s scheme of work before teaching begins.</p></div></div>{profile && <span className="inline-flex h-fit items-center gap-1.5 rounded-full bg-white px-3 py-1.5 text-[11px] font-bold text-[#176145] shadow-sm"><Check className="h-3.5 w-3.5" />Template applied</span>}</div>
    {profile && <div className="mt-4 rounded-xl border border-[#d9e8dc] bg-white px-4 py-3 text-xs text-[#496258]"><p className="font-semibold text-[#284539]">Current academic profile</p><p className="mt-1">{profile.templateId ?? "Custom school curriculum"} · {Array.isArray(profile.appliedClassIds) ? profile.appliedClassIds.length : 0} configured class{Array.isArray(profile.appliedClassIds) && profile.appliedClassIds.length === 1 ? "" : "es"}. Individual subjects remain editable by the school.</p></div>}
    {!canConfigure ? <div className="mt-5 flex gap-3 rounded-xl border border-[#e6dfc9] bg-[#fffaf0] p-4 text-xs leading-5 text-[#725b2d]"><LockKeyhole className="mt-0.5 h-4 w-4 shrink-0" />Only the school owner or an administrator can apply or change a curriculum template. Teachers can continue to use the approved classes and subjects for planning.</div> : <div className="mt-5 grid gap-4"><label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>Choose a reviewed template</span><select className={inputClass} value={templateId} onChange={event => { setTemplateId(event.target.value); setClassIds([]); }}><option value="">Select a curriculum starting point</option>{templates.data?.map(template => <option key={template.id} value={template.id}>{template.name} · {template.levelLabel}</option>)}</select></label>{selectedTemplate && <div className="rounded-xl border border-[#dce8de] bg-white p-4"><p className="text-xs font-semibold text-[#294238]">Subjects to review before applying</p><p className="mt-1 text-[11px] leading-5 text-[#66766e]">{selectedTemplate.reviewNote}</p><div className="mt-3 flex flex-wrap gap-2">{selectedTemplate.subjects.filter(subject => includeOptional || !subject.optional).map(subject => <span key={subject.code} className="rounded-full bg-[#edf3ed] px-2.5 py-1 text-[10px] font-semibold text-[#315247]">{subject.name}{subject.optional ? " · optional" : ""}</span>)}</div>{selectedTemplate.subjects.some(subject => subject.optional) && <label className="mt-4 flex items-center gap-2 text-xs font-semibold text-[#496258]"><input checked={includeOptional} onChange={event => setIncludeOptional(event.target.checked)} type="checkbox" className="h-4 w-4 accent-[#0f5c4f]" />Include the optional offerings in this reviewed setup</label>}</div>}
      {selectedTemplate && <div><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold text-[#43534c]">Apply to classes</p><button type="button" onClick={() => setClassIds((academic?.classes ?? []).map((item: any) => Number(item.id)))} className="text-xs font-bold text-[#0f5c4f]">Select all classes</button></div>{academic?.classes?.length ? <div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{academic.classes.map((item: any) => <label key={item.id} className="flex cursor-pointer items-center gap-2 rounded-lg border border-[#dfe7df] bg-white px-3 py-2 text-xs font-semibold text-[#3d5248]"><input checked={classIds.includes(Number(item.id))} onChange={() => toggleClass(Number(item.id))} type="checkbox" className="h-4 w-4 accent-[#0f5c4f]" />{item.name}{item.level ? ` · ${item.level}` : ""}</label>)}</div> : <p className="mt-2 rounded-lg border border-dashed border-[#d8e2d8] bg-white p-3 text-xs text-[#6d7b74]">Create your classes first, then return to apply this template.</p>}</div>}
      <button disabled={!templateId || !classIds.length || apply.isPending} onClick={() => apply.mutate({ schoolId, templateId: templateId as "basic_primary" | "basic_junior_secondary" | "senior_secondary_review", classIds, includeOptional })} className="inline-flex w-fit items-center gap-2 rounded-xl bg-[#0f5c4f] px-4 py-2.5 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50"><BookOpenCheck className="h-4 w-4" />{apply.isPending ? "Applying reviewed template…" : "Apply reviewed template"}</button>
    </div>}</section>;
}

export function SchoolBankAccountSetup({ schoolId, finance, canConfigure, onDone }: { schoolId: number; finance: any; canConfigure: boolean; onDone: () => void }) {
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ bankName: "", accountName: "", accountNumber: "", accountType: "current" as "current" | "savings" | "corporate" | "other", status: "draft" as "draft" | "active", isPrimary: true, paymentReferenceGuidance: "Use the student admission number as payment reference." });
  const create = trpc.nsos.finance.createBankAccount.useMutation({ onSuccess: () => { toast.success("Bank account saved. NSOS will only show the masked account number after setup."); setShowForm(false); setForm({ bankName: "", accountName: "", accountNumber: "", accountType: "current", status: "draft", isPrimary: true, paymentReferenceGuidance: "Use the student admission number as payment reference." }); onDone(); }, onError: error => toast.error(error.message) });
  const update = trpc.nsos.finance.updateBankAccountStatus.useMutation({ onSuccess: () => { toast.success("Bank account status updated."); onDone(); }, onError: error => toast.error(error.message) });
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate({ schoolId, ...form }); };
  return <section className="rounded-[1.2rem] border border-[#dae5dc] bg-white p-5 shadow-[0_10px_32px_rgba(16,45,35,0.035)] sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#eaf2ec] text-[#0f5c4f]"><Landmark className="h-5 w-5" /></span><div><p className="text-sm font-semibold text-[#294238]">Physical school bank accounts</p><p className="mt-1 max-w-2xl text-xs leading-5 text-[#64766b]">Publish safe transfer instructions for approved school accounts. Full account numbers are encrypted at rest and never returned by this screen after saving.</p></div></div>{canConfigure && <button onClick={() => setShowForm(current => !current)} className="inline-flex h-fit items-center gap-2 rounded-xl border border-[#cde0d0] bg-[#f7fbf7] px-3 py-2 text-xs font-bold text-[#0f5c4f]"><Plus className="h-3.5 w-3.5" />{showForm ? "Close setup" : "Add account"}</button>}</div>
    {showForm && <form onSubmit={submit} className="mt-5 grid gap-3 rounded-xl border border-[#dce7de] bg-[#f9fcf9] p-4 md:grid-cols-2"><label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>Bank name</span><input required className={inputClass} value={form.bankName} onChange={event => setForm({ ...form, bankName: event.target.value })} placeholder="e.g. First Bank of Nigeria" /></label><label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>Account name</span><input required className={inputClass} value={form.accountName} onChange={event => setForm({ ...form, accountName: event.target.value })} placeholder="Registered school account name" /></label><label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>10-digit account number</span><input required inputMode="numeric" pattern="[0-9 ]{10,24}" className={inputClass} value={form.accountNumber} onChange={event => setForm({ ...form, accountNumber: event.target.value.replace(/[^0-9 ]/g, "") })} placeholder="Stored encrypted" /></label><label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>Account type</span><select className={inputClass} value={form.accountType} onChange={event => setForm({ ...form, accountType: event.target.value as typeof form.accountType })}><option value="current">Current</option><option value="savings">Savings</option><option value="corporate">Corporate</option><option value="other">Other</option></select></label><label className="grid gap-1.5 text-xs font-semibold text-[#43534c] md:col-span-2"><span>Payment reference guidance</span><input className={inputClass} value={form.paymentReferenceGuidance} onChange={event => setForm({ ...form, paymentReferenceGuidance: event.target.value })} /></label><div className="md:col-span-2 flex flex-wrap gap-4"><label className="flex items-center gap-2 text-xs font-semibold text-[#43534c]"><input checked={form.status === "active"} onChange={event => setForm({ ...form, status: event.target.checked ? "active" : "draft" })} type="checkbox" className="h-4 w-4 accent-[#0f5c4f]" />Activate for school payment instructions</label><label className="flex items-center gap-2 text-xs font-semibold text-[#43534c]"><input checked={form.isPrimary} onChange={event => setForm({ ...form, isPrimary: event.target.checked })} type="checkbox" className="h-4 w-4 accent-[#0f5c4f]" />Make this the primary account</label></div><button disabled={create.isPending} className="inline-flex w-fit items-center gap-2 rounded-xl bg-[#0f5c4f] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><ShieldCheck className="h-4 w-4" />{create.isPending ? "Saving securely…" : "Save encrypted bank account"}</button></form>}
    {finance?.bankAccounts?.length ? <div className="mt-5 divide-y divide-[#edf0eb] border-t border-[#edf0eb]">{finance.bankAccounts.map((account: any) => <div key={account.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-[#294238]">{account.bankName}</p>{account.isPrimary && <span className="rounded-full bg-[#e2f1e8] px-2 py-1 text-[10px] font-bold text-[#176145]">Primary</span>}<span className="rounded-full bg-[#f0f3ef] px-2 py-1 text-[10px] font-semibold text-[#64746b]">{account.status}</span></div><p className="mt-1 text-xs text-[#66766e]">{account.accountName} · {account.accountNumberMasked} · {account.accountType}</p>{account.paymentReferenceGuidance && <p className="mt-1 text-[11px] text-[#50645a]">Reference: {account.paymentReferenceGuidance}</p>}</div>{canConfigure && account.status !== "archived" && <div className="flex gap-2">{account.status !== "active" && <button onClick={() => update.mutate({ schoolId, bankAccountId: account.id, status: "active", isPrimary: account.isPrimary })} className="rounded-lg border border-[#cde0d0] px-3 py-2 text-xs font-bold text-[#176145]">Activate</button>}<button onClick={() => update.mutate({ schoolId, bankAccountId: account.id, status: "archived" })} className="rounded-lg border border-[#ebd0cc] px-3 py-2 text-xs font-bold text-[#a13e38]">Archive</button></div>}</div>)}</div> : <div className="mt-5 rounded-xl border border-dashed border-[#d7e2d8] bg-[#fbfcfa] p-4 text-xs leading-5 text-[#697970]">No physical bank account has been configured. Add an owner-approved account before publishing bank-transfer instructions to families.</div>}
    {!canConfigure && <div className="mt-4 flex gap-2 rounded-xl border border-[#e8e0c8] bg-[#fffaf0] p-3 text-xs leading-5 text-[#735d2f]"><LockKeyhole className="mt-0.5 h-4 w-4 shrink-0" />Only the school owner or an administrator can add, activate, or archive bank-account instructions.</div>}
  </section>;
}
