import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Loader2, MessageSquare, Send } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const phonePattern = /^(?:\+?234|0|[1-9])(?:[\s()-]*\d){7,14}$/;

export function NotificationTestMessageDialog({ schoolId, provider, enabled, onSent }: { schoolId: number; provider: string; enabled: boolean; onSent: () => void }) {
  const [open, setOpen] = useState(false);
  const [phone, setPhone] = useState("");
  const [confirmed, setConfirmed] = useState(false);
  const [pendingLogId, setPendingLogId] = useState<number | null>(null);
  const [deliveryState, setDeliveryState] = useState<"pending" | "delivered" | "failed" | null>(null);
  const sendTest = trpc.nsos.providers.sendTestSms.useMutation({ onSuccess: result => { if (result.ok && "logId" in result && result.logId) { setPendingLogId(result.logId); setDeliveryState("pending"); toast.message(result.message); onSent(); } else { toast.error(result.message); } }, onError: error => toast.error(error.message) });
  const checkDelivery = trpc.nsos.providers.checkTestSmsDelivery.useMutation({ onSuccess: result => { setDeliveryState(result.deliveryState); result.deliveryState === "delivered" ? toast.success(result.message) : result.deliveryState === "failed" ? toast.error(result.message) : toast.message(result.message); onSent(); }, onError: error => toast.error(error.message) });
  const validPhone = phonePattern.test(phone.trim());
  const submit = () => sendTest.mutate({ schoolId, to: phone.trim(), confirmed: true });
  const checkStatus = () => { if (pendingLogId) checkDelivery.mutate({ schoolId, messageLogId: pendingLogId }); };

  return <Dialog open={open} onOpenChange={setOpen}>
    <button type="button" onClick={() => setOpen(true)} disabled={!enabled} title={enabled ? "Send one real SMS to verify delivery." : "Save Termii or Twilio as a ready notification provider first."} className="rounded-xl border border-[#c7b889] bg-[#fffaf0] px-4 py-2.5 text-sm font-bold text-[#855d14] disabled:cursor-not-allowed disabled:opacity-50"><MessageSquare className="mr-1.5 inline h-4 w-4" />Send test message</button>
    <DialogContent className="border-[#dde5dc] bg-[#fbfcfa] p-0 sm:max-w-[520px]" showCloseButton={!sendTest.isPending}>
      <DialogHeader className="border-b border-[#e3e9e2] p-6 pb-5"><div className="mb-2 grid h-10 w-10 place-items-center rounded-xl bg-[#fff1cf] text-[#8a5a12]"><MessageSquare className="h-5 w-5" /></div><DialogTitle className="text-[#20342c]">Send SMS delivery test</DialogTitle><DialogDescription className="leading-6 text-[#68766e]">NSOS will send one real test SMS through <strong className="capitalize text-[#334a40]">{provider.replace("_", " ")}</strong>. Use only a number you are authorized to contact.</DialogDescription></DialogHeader>
      <div className="grid gap-5 p-6"><label className="grid gap-2 text-xs font-bold text-[#43534c]"><span>Recipient mobile number</span><input value={phone} disabled={!!pendingLogId} onChange={event => setPhone(event.target.value)} inputMode="tel" autoComplete="tel" placeholder="0803 123 4567 or +234 803 123 4567" className="h-11 rounded-lg border border-[#dbe3da] bg-white px-3 text-sm text-[#20342c] outline-none focus:border-[#0f5c4f] focus:ring-2 focus:ring-[#0f5c4f]/10 disabled:bg-[#f1f4f0]" /><span className="font-normal leading-5 text-[#7a877f]">Nigerian numbers beginning with <code>080…</code> are normalized automatically. International format is also accepted.</span></label><label className="flex cursor-pointer gap-3 rounded-xl border border-[#ecd9a4] bg-[#fffaf0] p-4 text-xs leading-5 text-[#6e5a29]"><input type="checkbox" disabled={!!pendingLogId} checked={confirmed} onChange={event => setConfirmed(event.target.checked)} className="mt-0.5 h-4 w-4 rounded border-[#c9b673] accent-[#0f5c4f]" /><span><strong className="block text-[#69531e]">I confirm I am authorized to send this test.</strong> This creates one live SMS delivery request and may consume the school provider’s message credit.</span></label><div className="flex gap-2 rounded-lg bg-[#f1f5f0] px-3 py-2.5 text-xs leading-5 text-[#66766d]"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-[#8b6a1c]" /><span>The test message is clearly labelled as an NSOS configuration check. No student or guardian data is included.</span></div>{pendingLogId && <div className={`rounded-xl border p-4 text-xs leading-5 ${deliveryState === "delivered" ? "border-[#bdd7c2] bg-[#eef8f0] text-[#206143]" : deliveryState === "failed" ? "border-[#e5c4bf] bg-[#fff2f0] text-[#96463e]" : "border-[#d9cfaa] bg-[#fffbef] text-[#756028]"}`}><strong className="block">{deliveryState === "delivered" ? "Delivery confirmed" : deliveryState === "failed" ? "Delivery failed" : "SMS submitted — delivery pending"}</strong><span>{deliveryState === "delivered" ? "The provider reported that the test SMS was delivered." : deliveryState === "failed" ? "The provider reported that the message was not delivered." : "Use Check delivery status to request the provider’s latest delivery report."}</span></div>}</div>
      <DialogFooter className="border-t border-[#e3e9e2] bg-[#f7f9f6] p-5"><button type="button" onClick={() => setOpen(false)} disabled={sendTest.isPending || checkDelivery.isPending} className="rounded-xl px-4 py-2.5 text-sm font-bold text-[#64746b]">Close</button>{pendingLogId ? <button type="button" onClick={checkStatus} disabled={checkDelivery.isPending || deliveryState === "delivered" || deliveryState === "failed"} className="rounded-xl bg-[#0f5c4f] px-4 py-2.5 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">{checkDelivery.isPending ? <Loader2 className="mr-1.5 inline h-4 w-4 animate-spin" /> : <MessageSquare className="mr-1.5 inline h-4 w-4" />}Check delivery status</button> : <button type="button" onClick={submit} disabled={!validPhone || !confirmed || sendTest.isPending} className="rounded-xl bg-[#0f5c4f] px-4 py-2.5 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">{sendTest.isPending ? <Loader2 className="mr-1.5 inline h-4 w-4 animate-spin" /> : <Send className="mr-1.5 inline h-4 w-4" />}Send test SMS</button>}</DialogFooter>
    </DialogContent>
  </Dialog>;
}
