import { trpc } from "@/lib/trpc";
import { Building2, Download, FileText, Printer, UserRoundPlus } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const inputClass = "h-10 w-full rounded-lg border border-[#dfe5df] bg-[#fbfcfa] px-3 text-sm text-[#15201c] outline-none transition focus:border-[#0f5c4f] focus:ring-2 focus:ring-[#0f5c4f]/10";

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>{label}</span>{children}</label>;
}

function Card({ children }: { children: React.ReactNode }) {
  return <section className="rounded-[1.2rem] border border-[#e0e5df] bg-white p-5 shadow-[0_10px_32px_rgba(16,45,35,0.035)] sm:p-6">{children}</section>;
}

export function StudentLifecycleControls({ schoolId, students, onDone }: { schoolId: number; students: any[]; onDone: () => void }) {
  const [mode, setMode] = useState<"guardian" | "graduation">("guardian");
  const [studentId, setStudentId] = useState(""); const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const [relationship, setRelationship] = useState("Parent"); const [year, setYear] = useState(String(new Date().getFullYear()));
  const guardian = trpc.nsos.students.linkGuardian.useMutation({ onSuccess: () => { toast.success("Guardian linked to the student record."); onDone(); }, onError: error => toast.error(error.message) });
  const graduate = trpc.nsos.students.graduate.useMutation({ onSuccess: () => { toast.success("Student marked as graduated."); onDone(); }, onError: error => toast.error(error.message) });
  return <Card><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-[#2d4439]">Guardian & graduation records</p><p className="mt-1 text-xs text-[#758079]">Maintain family relationships and end-of-school transitions in the same learner record.</p></div><div className="flex gap-2"><button onClick={() => setMode("guardian")} className={`rounded-lg px-3 py-2 text-xs font-semibold ${mode === "guardian" ? "bg-[#0f5c4f] text-white" : "bg-[#f1f4f0] text-[#62726a]"}`}>Link guardian</button><button onClick={() => setMode("graduation")} className={`rounded-lg px-3 py-2 text-xs font-semibold ${mode === "graduation" ? "bg-[#0f5c4f] text-white" : "bg-[#f1f4f0] text-[#62726a]"}`}>Graduate</button></div></div>{mode === "guardian" ? <form onSubmit={(event: FormEvent) => { event.preventDefault(); guardian.mutate({ schoolId, studentId: Number(studentId), firstName, lastName, relationship, isPrimary: true }); }} className="mt-5 grid gap-3 sm:grid-cols-4"><Field label="Student"><select required className={inputClass} value={studentId} onChange={event => setStudentId(event.target.value)}><option value="">Select student</option>{students.map(item => <option value={item.id} key={item.id}>{item.firstName} {item.lastName}</option>)}</select></Field><Field label="Guardian first name"><input required className={inputClass} value={firstName} onChange={event => setFirstName(event.target.value)} /></Field><Field label="Guardian last name"><input required className={inputClass} value={lastName} onChange={event => setLastName(event.target.value)} /></Field><Field label="Relationship"><input required className={inputClass} value={relationship} onChange={event => setRelationship(event.target.value)} /></Field><button className="sm:col-span-4 w-fit rounded-xl bg-[#0f5c4f] px-4 py-2.5 text-sm font-bold text-white"><UserRoundPlus className="mr-2 inline h-4 w-4" />Link primary guardian</button></form> : <form onSubmit={(event: FormEvent) => { event.preventDefault(); graduate.mutate({ schoolId, studentId: Number(studentId), graduationYear: Number(year) }); }} className="mt-5 grid gap-3 sm:grid-cols-3"><Field label="Student"><select required className={inputClass} value={studentId} onChange={event => setStudentId(event.target.value)}><option value="">Select student</option>{students.map(item => <option value={item.id} key={item.id}>{item.firstName} {item.lastName}</option>)}</select></Field><Field label="Graduation year"><input required type="number" min="2000" max="2100" className={inputClass} value={year} onChange={event => setYear(event.target.value)} /></Field><button className="self-end w-fit rounded-xl bg-[#123b31] px-4 py-2.5 text-sm font-bold text-white">Confirm graduation</button></form>}</Card>;
}

export function AttendanceExport({ records }: { records: any[] }) {
  const exportCsv = () => {
    const csv = [["Attendance date", "Type", "Person record", "Status", "Note"], ...records.map(record => [new Date(record.attendanceDate).toLocaleDateString(), record.attendeeType, record.studentId ? `Student #${record.studentId}` : `Staff #${record.staffId}`, record.status, record.note ?? ""])].map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n");
    const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = "nsos-attendance-register.csv"; link.click(); URL.revokeObjectURL(link.href); toast.success("Attendance register exported.");
  };
  return <Card><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold text-[#2d4439]">Attendance export</p><p className="mt-1 text-xs text-[#758079]">Download the current register for school review and recordkeeping.</p></div><button onClick={exportCsv} className="rounded-xl border border-[#d8e2d9] bg-[#f6faf6] px-4 py-2.5 text-sm font-bold text-[#0f5c4f]"><Download className="mr-2 inline h-4 w-4" />Export CSV</button></div></Card>;
}

export function FinanceReceiptStation({ finance }: { finance: any }) {
  const [paymentId, setPaymentId] = useState("");
  const payment = finance?.payments?.find((item: any) => String(item.id) === paymentId);
  const printReceipt = () => {
    if (!payment) return;
    const popup = window.open("", "_blank", "noopener,noreferrer");
    if (!popup) return toast.error("Allow pop-ups to print the receipt.");
    popup.document.write(`<main style="font-family:Arial,sans-serif;max-width:620px;margin:42px auto;color:#16382f"><h1>NSOS Payment Receipt</h1><hr/><p><strong>Receipt:</strong> ${payment.receiptNo}</p><p><strong>Date:</strong> ${new Date(payment.paidOn).toLocaleDateString()}</p><p><strong>Method:</strong> ${payment.method}</p><p><strong>Amount:</strong> ₦${Number(payment.amount).toLocaleString("en-NG")}</p><p>This receipt was generated by Nigerian School Operating System.</p></main>`); popup.document.close(); popup.print();
  };
  return <Card><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-[#2d4439]">Receipt generation</p><p className="mt-1 text-xs text-[#758079]">Generate a printable receipt for any recorded payment.</p></div><div className="flex w-full gap-2 sm:w-auto"><select className={inputClass} value={paymentId} onChange={event => setPaymentId(event.target.value)}><option value="">Select payment</option>{finance?.payments?.map((item: any) => <option key={item.id} value={item.id}>{item.receiptNo} · ₦{Number(item.amount).toLocaleString("en-NG")}</option>)}</select><button onClick={printReceipt} disabled={!payment} className="shrink-0 rounded-xl bg-[#123b31] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Printer className="mr-2 inline h-4 w-4" />Print receipt</button></div></div></Card>;
}

export function ReportCardPrint({ schoolId, students, terms }: { schoolId: number; students: any[]; terms: any[] }) {
  const [studentId, setStudentId] = useState(""); const [termId, setTermId] = useState("");
  const report = trpc.nsos.results.reportCard.useQuery({ schoolId, studentId: Number(studentId || 0), termId: Number(termId || 0) }, { enabled: !!studentId && !!termId });
  const print = () => { if (!report.data) return; const popup = window.open("", "_blank", "noopener,noreferrer"); if (!popup) return toast.error("Allow pop-ups to print the report card."); const rows = report.data.entries.map((entry: any) => `<tr><td>${entry.subject}</td><td>${entry.assessment}</td><td>${entry.score ?? "—"}/${entry.maximumScore}</td><td>${entry.percentage ?? "—"}%</td></tr>`).join(""); popup.document.write(`<main style="font-family:Arial,sans-serif;max-width:760px;margin:42px auto;color:#16382f"><h1>NSOS Term Report Card</h1><p><strong>Student:</strong> ${report.data.student.firstName} ${report.data.student.lastName}</p><p><strong>Admission no.:</strong> ${report.data.student.admissionNo}</p><p><strong>Average:</strong> ${report.data.average ?? "—"}%</p><table style="width:100%;border-collapse:collapse" border="1" cellpadding="8"><thead><tr><th>Subject</th><th>Assessment</th><th>Score</th><th>Percentage</th></tr></thead><tbody>${rows}</tbody></table></main>`); popup.document.close(); popup.print(); };
  return <Card><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-[#2d4439]">Printable report card</p><p className="mt-1 text-xs text-[#758079]">Select a learner and term to print the computed assessment record.</p></div><div className="grid w-full gap-2 sm:w-auto sm:grid-cols-[180px_160px_auto]"><select className={inputClass} value={studentId} onChange={event => setStudentId(event.target.value)}><option value="">Select student</option>{students.map(item => <option key={item.id} value={item.id}>{item.firstName} {item.lastName}</option>)}</select><select className={inputClass} value={termId} onChange={event => setTermId(event.target.value)}><option value="">Select term</option>{terms.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button onClick={print} disabled={!report.data} className="rounded-xl bg-[#123b31] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Printer className="mr-2 inline h-4 w-4" />Print report</button></div></div></Card>;
}

export function DepartmentStation({ schoolId, onDone }: { schoolId: number; onDone: () => void }) {
  const [name, setName] = useState(""); const [code, setCode] = useState("");
  const create = trpc.nsos.staff.createDepartment.useMutation({ onSuccess: () => { toast.success("Department created."); setName(""); setCode(""); onDone(); }, onError: error => toast.error(error.message) });
  return <Card><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf3ed] text-[#0f5c4f]"><Building2 className="h-4 w-4" /></span><div><p className="text-sm font-semibold text-[#2d4439]">Departments & duties</p><p className="mt-1 text-xs text-[#758079]">Add departments first, then assign the department reference to staff profiles as the structure evolves.</p></div></div><form onSubmit={(event: FormEvent) => { event.preventDefault(); create.mutate({ schoolId, name, code: code || undefined }); }} className="mt-4 grid gap-3 sm:grid-cols-[1fr_180px_auto]"><Field label="Department name"><input required className={inputClass} value={name} onChange={event => setName(event.target.value)} placeholder="Academic Affairs" /></Field><Field label="Department code"><input className={inputClass} value={code} onChange={event => setCode(event.target.value.toUpperCase())} placeholder="ACA" /></Field><button className="self-end rounded-xl bg-[#0f5c4f] px-4 py-2.5 text-sm font-bold text-white">Create department</button></form></Card>;
}

export function MessageHistory({ schoolId }: { schoolId: number }) {
  const history = trpc.nsos.communications.history.useQuery({ schoolId });
  return <Card><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-semibold text-[#2d4439]">Message delivery history</p><p className="mt-1 text-xs text-[#758079]">Each record distinguishes a queued request, provider acceptance, and a recorded failure. A provider-accepted email is not presented as a confirmed inbox delivery.</p></div><FileText className="h-4 w-4 text-[#0f5c4f]" /></div>{history.isLoading ? <p className="mt-5 text-xs text-[#758079]">Loading message history…</p> : history.data?.length ? <div className="mt-4 divide-y divide-[#edf0eb] border-t border-[#edf0eb]">{history.data.slice(0, 12).map(item => { const failed = item.status === "failed"; const queued = item.status === "queued"; const label = failed ? "Failed — recover provider" : queued ? "Queued" : item.channel === "sms" ? "Provider accepted / tracked" : "Provider accepted"; const tone = failed ? "bg-[#f9e7e5] text-[#a13e38]" : queued ? "bg-[#f7eed9] text-[#8a5a12]" : "bg-[#e2f1e8] text-[#176145]"; return <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="text-xs font-semibold text-[#32473d]">{item.subject ?? "School message"}</p><p className="mt-1 text-[10px] text-[#7a847e]">{item.channel.replace("_", " ")} · {item.audience}{item.providerMessageId ? " · provider reference stored" : ""}</p>{failed && <p className="mt-1 text-[10px] font-medium text-[#9b413a]">Open the matching channel in Communication readiness, review credentials and sender verification, then use a deliberate retry path.</p>}</div><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${tone}`}>{label}</span></div>; })}</div> : <p className="mt-5 text-xs text-[#758079]">No messages have been logged yet.</p>}</Card>;
}
