import { trpc } from "@/lib/trpc";
import { ArrowRight, BadgeCheck, Banknote, CircleAlert, CreditCard, FileCheck2, Loader2, ShieldCheck, UsersRound } from "lucide-react";

type Handoff = "finance" | "admissions";

function EvidenceState({ label, detail, status }: { label: string; detail: string; status: "ready" | "waiting" | "blocked" }) {
  const tone = status === "ready" ? "border-[#bfe1c8] bg-[#f1fbf4] text-[#176145]" : status === "waiting" ? "border-[#f0dba4] bg-[#fffaf0] text-[#815d15]" : "border-[#ead1cc] bg-[#fff7f5] text-[#914b40]";
  const Icon = status === "ready" ? BadgeCheck : status === "waiting" ? CircleAlert : ShieldCheck;
  return <div className={`rounded-xl border p-3 ${tone}`}><div className="flex items-start gap-2"><Icon className="mt-0.5 h-4 w-4 shrink-0" /><div><p className="text-[11px] font-extrabold">{label}</p><p className="mt-1 text-[10px] leading-4 opacity-90">{detail}</p></div></div></div>;
}

export function PaymentEnrollmentReadiness({ schoolId, onNavigate }: { schoolId: number; onNavigate: (view: Handoff) => void }) {
  const providers = trpc.nsos.providers.list.useQuery({ schoolId });
  const cashAssurance = trpc.nsos.cashAssurance.list.useQuery({ schoolId });
  const applications = trpc.nsos.admissions.list.useQuery({ schoolId, limit: 100 });

  const paymentProvider = providers.data?.find(item => item.channel === "payment");
  const providerCredentialsStored = Boolean(paymentProvider?.hasCredentials);
  const providerReady = paymentProvider?.status === "ready" && providerCredentialsStored;
  const providerVerified = Boolean(paymentProvider?.lastValidatedAt);
  const evidence = cashAssurance.data?.paymentEvidence ?? [];
  const acceptedEvidence = evidence.filter(item => item.status === "accepted").length;
  const pendingEvidence = evidence.filter(item => item.status === "submitted" || item.status === "under_review").length;
  const acceptedApplications = (applications.data ?? []).filter(item => item.status === "accepted").length;
  const loading = providers.isLoading || cashAssurance.isLoading || applications.isLoading;
  const unavailable = providers.error || cashAssurance.error || applications.error;
  const providerLabel = paymentProvider?.provider ? paymentProvider.provider.replace(/_/g, " ") : "No provider selected";

  return <section className="overflow-hidden rounded-[1.35rem] border border-[#cddfd2] bg-white shadow-[0_10px_26px_rgba(23,72,49,.05)]" aria-label="Payment integration and enrollment readiness">
    <div className="border-b border-[#dce9df] bg-[linear-gradient(115deg,#f7fcf8,#eef8f1)] p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#0f5c4f] text-white"><CreditCard className="h-5 w-5" /></span><div><p className="text-sm font-extrabold text-[#214634]">Payment evidence & enrollment handoff</p><p className="mt-1 max-w-2xl text-[11px] leading-5 text-[#61766b]">Review sanitized provider readiness, payment-evidence review state, and accepted-application volume before using the separately protected finance and enrollment workspaces.</p></div></div><span className="inline-flex w-fit items-center gap-1.5 rounded-full border border-[#cee1d3] bg-white px-2.5 py-1 text-[10px] font-bold text-[#25684a]"><ShieldCheck className="h-3.5 w-3.5" />Owner review required</span></div></div>
    {loading ? <div className="grid min-h-44 place-items-center p-6" role="status" aria-live="polite"><div className="text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin text-[#0f5c4f]" /><p className="mt-3 text-xs font-semibold text-[#587065]">Checking payment and enrollment evidence…</p></div></div> : unavailable ? <div className="m-5 rounded-xl border border-[#ead5cb] bg-[#fff8f5] p-4 text-xs leading-5 text-[#884b42]" role="alert"><strong className="block text-[#793d35]">Evidence is temporarily unavailable.</strong><span>NSOS has not changed a provider, payment, or enrollment. Refresh the owner workspace, then use the established finance or admissions controls when the protected evidence queries return.</span></div> : <div className="grid gap-5 p-5 sm:p-6"><div className="grid gap-3 lg:grid-cols-3"><EvidenceState label="Provider configuration" status={providerReady ? "ready" : paymentProvider?.status === "disabled" ? "blocked" : "waiting"} detail={providerReady ? `${providerLabel} is marked ready; credentials are stored securely.` : paymentProvider?.status === "disabled" ? "The saved payment provider is disabled; it cannot support a live collection path." : "A provider may be selected as a draft, but live payment use remains unavailable until owner-controlled configuration is complete."} /><EvidenceState label="Provider verification evidence" status={providerVerified ? "ready" : providerReady ? "waiting" : "blocked"} detail={providerVerified ? `A connection check was recorded ${new Date(paymentProvider!.lastValidatedAt!).toLocaleString()}. The check did not collect a payment.` : providerReady ? "Credentials are saved, but no recorded connection check is available yet." : "No verified provider evidence exists for a payment-to-enrollment journey."} /><EvidenceState label="Payment-evidence review" status={acceptedEvidence > 0 ? "ready" : pendingEvidence > 0 ? "waiting" : "blocked"} detail={acceptedEvidence > 0 ? `${acceptedEvidence} payment-evidence record${acceptedEvidence === 1 ? " has" : "s have"} been accepted through the finance review workflow.` : pendingEvidence > 0 ? `${pendingEvidence} payment-evidence record${pendingEvidence === 1 ? " is" : "s are"} awaiting finance review.` : "No reviewed payment-evidence record is available. This does not imply a payment was made or missed."} /></div>
      <div className="grid gap-4 rounded-2xl border border-[#dbe9df] bg-[#fbfdfb] p-4 lg:grid-cols-[1fr_auto]"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#e6f4ea] text-[#1d704f]"><UsersRound className="h-4 w-4" /></span><div><p className="text-sm font-extrabold text-[#294c3b]">Enrollment remains a separate approval</p><p className="mt-1 max-w-2xl text-[11px] leading-5 text-[#61766b]">{acceptedApplications ? `${acceptedApplications} accepted application${acceptedApplications === 1 ? " is" : "s are"} available for an owner or authorized administrator to review in Admissions.` : "No accepted application is currently ready for enrollment review."} A provider status or payment-evidence record does not create a learner, alter an application, assign a class, send an admission letter, or confirm enrollment from this panel.</p></div></div><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={() => onNavigate("finance")} className="inline-flex min-h-10 items-center gap-1.5 rounded-xl border border-[#b7d1bf] bg-white px-3 text-xs font-extrabold text-[#176145] transition hover:bg-[#f1faf3]"><Banknote className="h-3.5 w-3.5" />Review finance evidence</button><button type="button" onClick={() => onNavigate("admissions")} className="inline-flex min-h-10 items-center gap-1.5 rounded-xl bg-[#0f5c4f] px-3 text-xs font-extrabold text-white transition hover:bg-[#0b4a3e]"><FileCheck2 className="h-3.5 w-3.5" />Review admissions <ArrowRight className="h-3.5 w-3.5" /></button></div></div>
      <div className="rounded-xl border border-[#e6d9aa] bg-[#fffaf0] p-4 text-[11px] leading-5 text-[#725d2e]"><strong className="text-[#644b18]">Activation boundary.</strong> This panel displays only sanitized readiness and aggregate review evidence. It cannot save merchant credentials, run a provider test, collect or record a payment, approve payment evidence, accept an applicant, enroll a learner, issue a receipt, or send an admission letter. Those actions remain in their own protected, confirmation-gated workflows.</div>
    </div>}
  </section>;
}
