import { CreditCard, Landmark, Loader2, Plus, RefreshCw, ShieldCheck, X } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const money = (value: number | string) => new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(Number(value));
const today = () => new Date().toISOString().slice(0, 10);

export function PlatformRevenueConsole({ open, onClose }: { open: boolean; onClose: () => void }) {
  const utils = trpc.useUtils();
  const overview = trpc.nsos.platformRevenue.overview.useQuery(undefined, { enabled: open });
  const [planCode, setPlanCode] = useState("");
  const [planName, setPlanName] = useState("");
  const [monthlyAmount, setMonthlyAmount] = useState("");
  const [annualAmount, setAnnualAmount] = useState("");
  const [selectedSchoolId, setSelectedSchoolId] = useState("");
  const [selectedPlanId, setSelectedPlanId] = useState("");
  const [billingCycle, setBillingCycle] = useState<"monthly" | "annual">("monthly");
  const [subscriptionStatus, setSubscriptionStatus] = useState<"trial" | "active" | "payment_due" | "suspended" | "cancelled">("trial");
  const [affiliateCode, setAffiliateCode] = useState("");
  const [affiliateName, setAffiliateName] = useState("");
  const [affiliateDestination, setAffiliateDestination] = useState("");
  const [affiliateCommissionType, setAffiliateCommissionType] = useState<"percentage" | "fixed">("percentage");
  const [affiliateCommissionValue, setAffiliateCommissionValue] = useState("");
  const [affiliateAttributionDays, setAffiliateAttributionDays] = useState("30");
  const [affiliatePartnerId, setAffiliatePartnerId] = useState("");
  const [affiliatePeriodStart, setAffiliatePeriodStart] = useState("");
  const [affiliatePeriodEnd, setAffiliatePeriodEnd] = useState("");

  const refresh = () => void utils.nsos.platformRevenue.overview.invalidate();
  const createPlan = trpc.nsos.platformRevenue.createPlan.useMutation({ onSuccess: () => { toast.success("Subscription plan created."); setPlanCode(""); setPlanName(""); setMonthlyAmount(""); setAnnualAmount(""); refresh(); }, onError: error => toast.error(error.message) });
  const assignSubscription = trpc.nsos.platformRevenue.assignSubscription.useMutation({ onSuccess: () => { toast.success("School subscription updated."); refresh(); }, onError: error => toast.error(error.message) });
  const issueBilling = trpc.nsos.platformRevenue.issueBillingRecord.useMutation({ onSuccess: () => { toast.success("Platform billing record issued."); refresh(); }, onError: error => toast.error(error.message) });
  const settleBilling = trpc.nsos.platformRevenue.recordBillingPayment.useMutation({ onSuccess: () => { toast.success("Payment recorded after verification."); refresh(); }, onError: error => toast.error(error.message) });
  const affiliatePartners = trpc.nsos.affiliates.partners.list.useQuery(undefined, { enabled: open });
  const affiliateConversions = trpc.nsos.affiliates.conversions.list.useQuery(undefined, { enabled: open });
  const affiliatePayouts = trpc.nsos.affiliates.payouts.list.useQuery(undefined, { enabled: open });
  const refreshAffiliate = () => { void affiliatePartners.refetch(); void affiliateConversions.refetch(); void affiliatePayouts.refetch(); };
  const createAffiliate = trpc.nsos.affiliates.partners.create.useMutation({ onSuccess: () => { toast.success("Affiliate partner created."); setAffiliateCode(""); setAffiliateName(""); setAffiliateDestination(""); setAffiliateCommissionValue(""); refreshAffiliate(); }, onError: error => toast.error(error.message) });
  const approveAffiliate = trpc.nsos.affiliates.conversions.approve.useMutation({ onSuccess: () => { toast.success("Conversion approved."); refreshAffiliate(); }, onError: error => toast.error(error.message) });
  const createAffiliatePayout = trpc.nsos.affiliates.payouts.create.useMutation({ onSuccess: () => { toast.success("Affiliate payout ledger created."); refreshAffiliate(); }, onError: error => toast.error(error.message) });
  const settleAffiliatePayout = trpc.nsos.affiliates.payouts.updateStatus.useMutation({ onSuccess: () => { toast.success("Affiliate payout status updated."); refreshAffiliate(); }, onError: error => toast.error(error.message) });

  const selectedSchool = useMemo(() => overview.data?.schools.find(school => String(school.id) === selectedSchoolId), [overview.data?.schools, selectedSchoolId]);
  if (!open) return null;
  const submitPlan = (event: FormEvent) => { event.preventDefault(); createPlan.mutate({ code: planCode, name: planName, monthlyAmount: Number(monthlyAmount || 0), annualAmount: Number(annualAmount || 0) }); };
  const submitSubscription = (event: FormEvent) => { event.preventDefault(); if (!selectedSchoolId || !selectedPlanId) return toast.error("Select a school and an active plan."); assignSubscription.mutate({ schoolId: Number(selectedSchoolId), planId: Number(selectedPlanId), status: subscriptionStatus, billingCycle }); };
  const submitAffiliate = (event: FormEvent) => { event.preventDefault(); createAffiliate.mutate({ code: affiliateCode, name: affiliateName, destinationUrl: affiliateDestination, commissionType: affiliateCommissionType, commissionValue: affiliateCommissionValue, attributionDays: Number(affiliateAttributionDays || 30) }); };
  const submitAffiliatePayout = (event: FormEvent) => { event.preventDefault(); if (!affiliatePartnerId || !affiliatePeriodStart || !affiliatePeriodEnd) return toast.error("Select a partner and payout period."); createAffiliatePayout.mutate({ partnerId: Number(affiliatePartnerId), periodStart: affiliatePeriodStart, periodEnd: affiliatePeriodEnd }); };

  return <div className="fixed inset-0 z-[80] overflow-y-auto bg-[#0a1713]/55 p-3 backdrop-blur-sm sm:p-6" role="dialog" aria-modal="true" aria-label="NSOS revenue administration">
    <div className="mx-auto max-w-6xl rounded-[1.4rem] border border-[#dbe5dc] bg-[#f7f8f4] shadow-2xl">
      <div className="flex items-start justify-between gap-5 border-b border-[#dfe5df] bg-white px-5 py-5 sm:px-7"><div><div className="flex items-center gap-2 text-[#0f5c4f]"><ShieldCheck className="h-4 w-4" /><p className="mono text-[10px] font-semibold uppercase tracking-[0.16em]">Operator-only revenue workspace</p></div><h2 className="mt-2 text-xl font-semibold tracking-[-0.04em] text-[#173128]">School subscriptions and onboarding billing</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-[#68736d]">This records plans and verified commercial status. It does not charge a card or suspend school operations automatically.</p></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-lg border border-[#dfe5df] text-[#51635a] hover:bg-[#f4f6f2]" aria-label="Close revenue console"><X className="h-4 w-4" /></button></div>
      {overview.isLoading ? <div className="grid min-h-80 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-[#0f5c4f]" /></div> : overview.error ? <div className="p-8 text-sm text-[#a13e38]">{overview.error.message}</div> : <div className="grid gap-6 p-5 sm:p-7">
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Schools" value={String(overview.data?.metrics.schoolCount ?? 0)} /><Metric label="Active" value={String(overview.data?.metrics.activeSubscriptions ?? 0)} /><Metric label="Payment due" value={String(overview.data?.metrics.paymentDueSubscriptions ?? 0)} /><Metric label="Invoiced" value={money(overview.data?.metrics.invoiced ?? 0)} /><Metric label="Collected" value={money(overview.data?.metrics.collected ?? 0)} /></div>
        <div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><section className="rounded-2xl border border-[#dfe5df] bg-white p-5"><div className="flex items-center gap-2"><Plus className="h-4 w-4 text-[#0f5c4f]" /><h3 className="text-sm font-semibold text-[#20342c]">Create a commercial plan</h3></div><p className="mt-1 text-xs leading-5 text-[#758079]">Only the NSOS operator sets product prices. Schools never see or change plan pricing here.</p><form className="mt-5 grid gap-3" onSubmit={submitPlan}><Input label="Plan code" value={planCode} onChange={setPlanCode} placeholder="GROWTH" required /><Input label="Plan name" value={planName} onChange={setPlanName} placeholder="Growth" required /><div className="grid gap-3 sm:grid-cols-2"><Input label="Monthly price (NGN)" value={monthlyAmount} onChange={setMonthlyAmount} type="number" placeholder="0" required /><Input label="Annual price (NGN)" value={annualAmount} onChange={setAnnualAmount} type="number" placeholder="0" required /></div><button disabled={createPlan.isPending} className="mt-1 inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[#0f5c4f] text-sm font-semibold text-white disabled:opacity-60"><Plus className="h-4 w-4" />Create plan</button></form></section>
          <section className="rounded-2xl border border-[#dfe5df] bg-white p-5"><div className="flex items-center gap-2"><Landmark className="h-4 w-4 text-[#0f5c4f]" /><h3 className="text-sm font-semibold text-[#20342c]">Assign commercial status</h3></div><form className="mt-5 grid gap-3" onSubmit={submitSubscription}><Select label="School" value={selectedSchoolId} onChange={setSelectedSchoolId} placeholder="Select a school" options={(overview.data?.schools ?? []).map(school => ({ value: String(school.id), label: `${school.name} · ${school.shortCode}` }))} /><Select label="Active plan" value={selectedPlanId} onChange={setSelectedPlanId} placeholder="Select a plan" options={(overview.data?.plans ?? []).filter(plan => plan.status === "active").map(plan => ({ value: String(plan.id), label: `${plan.name} · ${money(plan.monthlyAmount)}/month` }))} /><div className="grid gap-3 sm:grid-cols-2"><Select label="Commercial state" value={subscriptionStatus} onChange={value => setSubscriptionStatus(value as typeof subscriptionStatus)} options={["trial", "active", "payment_due", "suspended", "cancelled"].map(value => ({ value, label: value.replace("_", " ") }))} /><Select label="Billing cycle" value={billingCycle} onChange={value => setBillingCycle(value as typeof billingCycle)} options={[{ value: "monthly", label: "Monthly" }, { value: "annual", label: "Annual" }]} /></div><button disabled={assignSubscription.isPending} className="mt-1 inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[#102a24] text-sm font-semibold text-white disabled:opacity-60">Save commercial status</button></form></section></div>
        <section className="grid gap-6 rounded-2xl border border-[#dfe5df] bg-white p-5">
          <div><p className="mono text-[10px] font-semibold uppercase tracking-[0.14em] text-[#0f5c4f]">Affiliate / referral engine</p><h3 className="mt-1 text-base font-semibold text-[#20342c]">Partner attribution and commission ledger</h3><p className="mt-1 text-xs leading-5 text-[#758079]">Configure the real partner destination and commercial terms when an agreement exists. NSOS does not invent partner URLs or move payout funds automatically.</p></div>
          <div className="grid gap-6 xl:grid-cols-[.95fr_1.05fr]">
            <form className="grid gap-3 rounded-xl border border-[#e4e9e3] bg-[#fbfcfa] p-4" onSubmit={submitAffiliate}>
              <Input label="Partner code" value={affiliateCode} onChange={setAffiliateCode} placeholder="partner-name" required />
              <Input label="Partner name" value={affiliateName} onChange={setAffiliateName} placeholder="Partner organisation" required />
              <Input label="Destination URL" value={affiliateDestination} onChange={setAffiliateDestination} placeholder="https://partner.example/..." required />
              <div className="grid gap-3 sm:grid-cols-2"><Select label="Commission" value={affiliateCommissionType} onChange={value => setAffiliateCommissionType(value as typeof affiliateCommissionType)} options={[{ value: "percentage", label: "Percentage" }, { value: "fixed", label: "Fixed amount" }]} /><Input label="Commission value" value={affiliateCommissionValue} onChange={setAffiliateCommissionValue} placeholder="10" required /></div>
              <Input label="Attribution window (days)" value={affiliateAttributionDays} onChange={setAffiliateAttributionDays} type="number" placeholder="30" required />
              <button disabled={createAffiliate.isPending} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[#0f5c4f] text-sm font-semibold text-white disabled:opacity-60"><Plus className="h-4 w-4" />Create partner</button>
            </form>
            <div className="grid gap-3">
              {(affiliatePartners.data ?? []).map(partner => <div key={partner.id} className="rounded-xl border border-[#e4e9e3] bg-[#fbfcfa] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-[#20342c]">{partner.name}</p><p className="mt-1 text-[11px] text-[#78837d]"><code>/r/{partner.code}</code> · {partner.commissionValue}{partner.commissionType === "percentage" ? "%" : " " + partner.currency} · {partner.status}</p></div><button onClick={() => navigator.clipboard?.writeText(window.location.origin + "/r/" + partner.code)} className="rounded-lg border border-[#dfe5df] px-2.5 py-1.5 text-[11px] font-semibold text-[#486057]">Copy link</button></div></div>)}
              {!affiliatePartners.data?.length && <div className="rounded-xl border border-dashed border-[#dfe5df] p-6 text-center text-xs text-[#758079]">No affiliate partner is configured yet.</div>}
            </div>
          </div>
          <div className="grid gap-6 xl:grid-cols-2">
            <section className="rounded-xl border border-[#e4e9e3] p-4"><div className="flex items-center justify-between"><h4 className="text-sm font-semibold text-[#20342c]">Conversions</h4><span className="text-xs text-[#758079]">{affiliateConversions.data?.length ?? 0}</span></div><div className="mt-3 space-y-2">{(affiliateConversions.data ?? []).slice(0, 8).map(conversion => <div key={conversion.id} className="flex items-center justify-between gap-3 rounded-lg bg-[#f7f9f6] p-3"><div><p className="text-xs font-semibold text-[#334a40]">{conversion.eventType}</p><p className="text-[10px] text-[#7a847e]">{conversion.externalReference} · {conversion.currency} {conversion.commissionAmount}</p></div>{conversion.status === "pending" && <button onClick={() => approveAffiliate.mutate({ id: conversion.id })} className="rounded-lg bg-[#eff8f0] px-2.5 py-1.5 text-[11px] font-semibold text-[#176145]">Approve</button>}</div>)}{!affiliateConversions.data?.length && <p className="py-4 text-xs text-[#758079]">No conversions recorded.</p>}</div></section>
            <section className="rounded-xl border border-[#e4e9e3] p-4"><h4 className="text-sm font-semibold text-[#20342c]">Create payout ledger</h4><form className="mt-3 grid gap-3" onSubmit={submitAffiliatePayout}><Select label="Partner" value={affiliatePartnerId} onChange={setAffiliatePartnerId} placeholder="Select partner" options={(affiliatePartners.data ?? []).map(partner => ({ value: String(partner.id), label: partner.name }))} /><div className="grid gap-3 sm:grid-cols-2"><Input label="Period start" value={affiliatePeriodStart} onChange={setAffiliatePeriodStart} type="date" required /><Input label="Period end" value={affiliatePeriodEnd} onChange={setAffiliatePeriodEnd} type="date" required /></div><button disabled={createAffiliatePayout.isPending} className="h-10 rounded-xl bg-[#102a24] text-sm font-semibold text-white disabled:opacity-60">Build payout ledger</button></form><div className="mt-4 space-y-2">{(affiliatePayouts.data ?? []).slice(0, 5).map(payout => <div key={payout.id} className="flex items-center justify-between gap-3 rounded-lg bg-[#f7f9f6] p-3"><div><p className="text-xs font-semibold text-[#334a40]">{payout.currency} {payout.amount}</p><p className="text-[10px] text-[#7a847e]">{payout.periodStart} → {payout.periodEnd} · {payout.status}</p></div>{payout.status === "pending" && <button onClick={() => settleAffiliatePayout.mutate({ id: payout.id, status: "approved" })} className="rounded-lg bg-[#eff8f0] px-2.5 py-1.5 text-[11px] font-semibold text-[#176145]">Approve</button>}{payout.status === "approved" && <button onClick={() => settleAffiliatePayout.mutate({ id: payout.id, status: "paid", paymentReference: "manual-verified" })} className="rounded-lg bg-[#f1f8f1] px-2.5 py-1.5 text-[11px] font-semibold text-[#176145]">Mark paid</button>}</div>)}</div></section>
          </div>
        </section>
        <section className="overflow-hidden rounded-2xl border border-[#dfe5df] bg-white"><div className="flex items-center justify-between gap-3 border-b border-[#e8ece7] px-5 py-4"><div><h3 className="text-sm font-semibold text-[#20342c]">Tenant commercial register</h3><p className="mt-0.5 text-xs text-[#758079]">Issue an onboarding or renewal record only after a plan is assigned. Mark payment paid only after independent verification.</p></div><button onClick={refresh} className="rounded-lg border border-[#dfe5df] p-2 text-[#577067] hover:bg-[#f5f7f4]" aria-label="Refresh revenue data"><RefreshCw className="h-3.5 w-3.5" /></button></div>{overview.data?.schools.length ? <div className="divide-y divide-[#edf0ec]">{overview.data.schools.map(school => <div key={school.id} className="grid gap-3 px-5 py-4 lg:grid-cols-[1.2fr_.8fr_.8fr_1fr]"><div><p className="text-sm font-semibold text-[#253b31]">{school.name}</p><p className="mt-0.5 text-[11px] text-[#78837d]">{school.shortCode} · {school.state ?? "State not set"}</p></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#8a948e]">Plan</p><p className="mt-1 text-xs font-semibold text-[#355044]">{school.plan?.name ?? "Unassigned"}</p></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#8a948e]">State</p><p className="mt-1 text-xs font-semibold capitalize text-[#355044]">{school.subscription?.status?.replace("_", " ") ?? "Trial"}</p></div><div className="flex flex-wrap items-center gap-2 lg:justify-end">{school.subscription?.planId && <button disabled={issueBilling.isPending} onClick={() => issueBilling.mutate({ schoolId: school.id, issueDate: today() })} className="rounded-lg border border-[#cfe0d2] bg-[#f1f8f1] px-3 py-2 text-xs font-semibold text-[#176145] disabled:opacity-60">Issue billing</button>}{school.billingRecords.filter(record => record.status === "issued").slice(0, 1).map(record => <button key={record.id} disabled={settleBilling.isPending} onClick={() => settleBilling.mutate({ billingRecordId: record.id, paidAt: today(), paymentMethod: "manual" })} className="rounded-lg border border-[#e8dcbf] bg-[#fbf5e8] px-3 py-2 text-xs font-semibold text-[#805615] disabled:opacity-60">Mark verified paid</button>)}</div></div>)}</div> : <div className="p-10 text-center text-sm text-[#758079]">Schools appear here only after a real tenant workspace is created.</div>}</section>
      </div>}
    </div>
  </div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[#dfe5df] bg-white p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#7b8780]">{label}</p><p className="mt-2 text-xl font-semibold tracking-[-0.04em] text-[#173128]">{value}</p></div>; }
function Input({ label, value, onChange, placeholder, type = "text", required = false }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string; required?: boolean }) { return <label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>{label}</span><input required={required} type={type} min={type === "number" ? 0 : undefined} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="h-10 rounded-lg border border-[#dfe5df] bg-[#fbfcfa] px-3 text-sm outline-none focus:border-[#0f5c4f] focus:ring-2 focus:ring-[#0f5c4f]/10" /></label>; }
function Select({ label, value, onChange, options, placeholder }: { label: string; value: string; onChange: (value: string) => void; options: { value: string; label: string }[]; placeholder?: string }) { return <label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>{label}</span><select value={value} onChange={event => onChange(event.target.value)} className="h-10 rounded-lg border border-[#dfe5df] bg-[#fbfcfa] px-3 text-sm outline-none focus:border-[#0f5c4f] focus:ring-2 focus:ring-[#0f5c4f]/10">{placeholder && <option value="">{placeholder}</option>}{options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
