import { trpc } from "@/lib/trpc";
import { ClipboardCheck, ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const inputClass = "h-10 w-full rounded-lg border border-[#dfe5df] bg-[#fbfcfa] px-3 text-sm text-[#15201c] outline-none transition focus:border-[#0f5c4f] focus:ring-2 focus:ring-[#0f5c4f]/10";

export function AdmissionDocumentReview({ schoolId, applications, onDone }: { schoolId: number; applications: any[]; onDone: () => void }) {
  const [applicationId, setApplicationId] = useState("");
  const documents = trpc.nsos.admissions.documents.useQuery({ schoolId, applicationId: Number(applicationId || 0) }, { enabled: !!applicationId });
  const review = trpc.nsos.admissions.reviewDocument.useMutation({ onSuccess: () => { toast.success("Document review recorded."); documents.refetch(); onDone(); }, onError: error => toast.error(error.message) });
  return <section className="rounded-[1.2rem] border border-[#e0e5df] bg-white p-5 shadow-[0_10px_32px_rgba(16,45,35,0.035)] sm:p-6"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#f7eed9] text-[#8a5a12]"><ClipboardCheck className="h-4 w-4" /></span><div><p className="text-sm font-semibold text-[#2d4439]">Document review</p><p className="mt-1 text-xs text-[#758079]">Verify or reject files attached to an admissions application before final enrollment. Receipt evidence is not a payment approval.</p></div></div><label className="mt-5 grid max-w-md gap-1.5 text-xs font-semibold text-[#43534c]"><span>Application</span><select className={inputClass} value={applicationId} onChange={event => setApplicationId(event.target.value)}><option value="">Select application</option>{applications.map(item => <option value={item.id} key={item.id}>{item.applicationNo} · {item.firstName} {item.lastName}</option>)}</select></label>{documents.isLoading ? <p className="mt-4 text-xs text-[#758079]">Loading documents…</p> : documents.data?.length ? <div className="mt-5 divide-y divide-[#edf0eb] border-t border-[#edf0eb]">{documents.data.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><a className="text-xs font-semibold text-[#0f5c4f] underline" href={item.url} target="_blank" rel="noreferrer">{item.label}</a><p className="mt-1 text-[10px] text-[#7a847e]">{item.documentType === "passport_photo" ? "Passport photograph" : item.documentType === "admission_fee_receipt" ? "Admission-fee receipt" : "Supporting document"} · {item.mimeType ?? "Document"}{item.byteSize ? ` · ${Math.ceil(item.byteSize / 1024)} KB` : ""} · {item.status}</p></div><div className="flex gap-2"><button onClick={() => review.mutate({ schoolId, documentId: item.id, status: "verified" })} className="rounded-lg bg-[#e2f1e8] px-3 py-1.5 text-xs font-bold text-[#176145]">Verify</button><button onClick={() => review.mutate({ schoolId, documentId: item.id, status: "rejected" })} className="rounded-lg bg-[#f9e7e5] px-3 py-1.5 text-xs font-bold text-[#a13e38]">Reject</button></div></div>)}</div> : applicationId ? <p className="mt-4 text-xs text-[#758079]">No supporting documents have been uploaded for this application.</p> : null}</section>;
}

export function ResultApprovalControl({ schoolId, academic, onDone }: { schoolId: number; academic: any; onDone: () => void }) {
  const [termId, setTermId] = useState(""); const [classId, setClassId] = useState("");
  const approve = trpc.nsos.results.approve.useMutation({ onSuccess: () => { toast.success("Class results approved for publication."); onDone(); }, onError: error => toast.error(error.message) });
  return <section className="rounded-[1.2rem] border border-[#e0e5df] bg-white p-5 shadow-[0_10px_32px_rgba(16,45,35,0.035)] sm:p-6"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e2f0f3] text-[#216574]"><ShieldCheck className="h-4 w-4" /></span><div><p className="text-sm font-semibold text-[#2d4439]">Results approval gate</p><p className="mt-1 text-xs text-[#758079]">An authorized reviewer must approve a term and class before the publishing action is permitted.</p></div></div><form onSubmit={(event: FormEvent) => { event.preventDefault(); approve.mutate({ schoolId, termId: Number(termId), classId: Number(classId) }); }} className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>Term</span><select required className={inputClass} value={termId} onChange={event => setTermId(event.target.value)}><option value="">Select term</option>{(academic?.terms ?? []).map((item: any) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>Class</span><select required className={inputClass} value={classId} onChange={event => setClassId(event.target.value)}><option value="">Select class</option>{(academic?.classes ?? []).map((item: any) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><button className="self-end rounded-xl bg-[#123b31] px-4 py-2.5 text-sm font-bold text-white">Approve results</button></form></section>;
}
