import { trpc } from "@/lib/trpc";
import { Flag, FlagOff, ShieldAlert } from "lucide-react";
import { toast } from "sonner";

type RevisionAlert = { id: number; classLabel: string; subjectLabel: string; termLabel: string; recipientName?: string | null; recommendedAt: Date | null; createdAt: Date };

export function TeacherRecommendedPriorityNotice({ schoolId }: { schoolId: number }) {
  const alerts = trpc.nsos.academics.schemeRevisionNotifications.useQuery({ schoolId });
  const recommended = ((alerts.data ?? []) as RevisionAlert[]).filter(alert => Boolean(alert.recommendedAt));
  if (!recommended.length) return null;
  return <section className="rounded-[1.2rem] border border-[#dfc47e] bg-[#fff8e7] p-4 shadow-[0_8px_24px_rgba(106,75,11,0.05)]"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#f4dfa7] text-[#725212]"><ShieldAlert className="h-4.5 w-4.5" /></span><div><p className="text-xs font-bold text-[#5c4310]">School leader recommends priority review</p><p className="mt-1 text-[11px] leading-5 text-[#765d25]">{recommended.length === 1 ? "One revised weekly plan" : `${recommended.length} revised weekly plans`} has been marked as a recommended priority. It remains your decision whether to pin it personally.</p><div className="mt-2 flex flex-wrap gap-1.5">{recommended.slice(0, 3).map(alert => <span key={alert.id} className="rounded-full border border-[#e5ce90] bg-white/80 px-2 py-1 text-[10px] font-bold text-[#755916]">{alert.classLabel} · {alert.subjectLabel}</span>)}</div></div></div></section>;
}

export function LeaderSchemeRevisionPriorityControls({ schoolId, onDone }: { schoolId: number; onDone: () => void }) {
  const alerts = trpc.nsos.academics.schemeRevisionNotificationsForManagement.useQuery({ schoolId });
  const recommend = trpc.nsos.academics.setSchemeRevisionNotificationRecommended.useMutation({ onSuccess: result => { toast.success(result.recommended ? "Recommended priority set for the assigned teacher." : "Leader recommendation cleared."); alerts.refetch(); onDone(); }, onError: error => toast.error(error.message) });
  const rows = (alerts.data ?? []) as RevisionAlert[];
  const recommendedCount = rows.filter(row => row.recommendedAt).length;
  return <section className="rounded-[1.2rem] border border-[#ead6a0] bg-white p-5 shadow-[0_10px_32px_rgba(16,45,35,0.035)] sm:p-6"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#fff1c9] text-[#785714]"><Flag className="h-5 w-5" /></span><div><p className="text-sm font-semibold text-[#413516]">Leader-recommended revision priorities</p><p className="mt-1 text-xs leading-5 text-[#716034]">Flag a specific re-import alert when the assigned teacher should give it prompt attention. This is separate from the teacher’s own pin and does not publish or approve any plan.</p></div></div>{rows.length ? <div className="mt-4 grid gap-2">{rows.slice(0, 12).map(alert => <div key={alert.id} className={`flex flex-col gap-3 rounded-xl border p-3 sm:flex-row sm:items-center sm:justify-between ${alert.recommendedAt ? "border-[#d9b65f] bg-[#fffdf5]" : "border-[#e8e5da] bg-[#fbfcfa]"}`}><div><div className="flex flex-wrap items-center gap-1.5"><p className="text-xs font-bold text-[#384b41]">{alert.classLabel} · {alert.subjectLabel} · {alert.termLabel}</p>{alert.recommendedAt ? <span className="inline-flex items-center gap-1 rounded-full bg-[#f3dfa9] px-2 py-0.5 text-[9px] font-bold text-[#765412]"><Flag className="h-2.5 w-2.5" />Recommended</span> : null}</div><p className="mt-1 text-[11px] text-[#6a7971]">Assigned teacher: {alert.recipientName || "Teacher"} · Re-imported {new Date(alert.createdAt).toLocaleString()}</p></div><button type="button" disabled={recommend.isPending} onClick={() => recommend.mutate({ schoolId, notificationId: alert.id, recommended: !alert.recommendedAt })} className="inline-flex w-fit items-center gap-1.5 rounded-lg border border-[#d9be78] bg-white px-3 py-2 text-xs font-bold text-[#725412] disabled:opacity-50">{alert.recommendedAt ? <><FlagOff className="h-3.5 w-3.5" />Clear priority</> : <><Flag className="h-3.5 w-3.5" />Recommend priority</>}</button></div>)}</div> : <div className="mt-4 rounded-xl border border-dashed border-[#dccb9a] bg-[#fffaf0] p-4 text-xs leading-5 text-[#765d25]">No revised scheme alerts are currently available to recommend. This panel will populate after a scheme is replaced and its assigned teacher is notified.</div>}{recommendedCount ? <p className="mt-3 text-[11px] font-semibold text-[#715417]">{recommendedCount} alert{recommendedCount === 1 ? "" : "s"} currently marked as leader-recommended priority.</p> : null}</section>;
}
