import { Activity, ArrowRight, BrainCircuit, CircleAlert, ClipboardCheck, Loader2, RefreshCw, ShieldCheck, WalletCards, X } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type Destination = "overview" | "learning" | "admissions" | "finance" | "communications" | "automation" | "website" | "institution-builder";

const tone: Record<string, string> = { info: "border-[#c7e4d1] bg-[#f2fbf5] text-[#216044]", attention: "border-[#ead9a6] bg-[#fffaf0] text-[#785f2c]", review: "border-[#efc6be] bg-[#fff5f2] text-[#8d4137]" };

export function SchoolOperator({ schoolId, onNavigate }: { schoolId: number; onNavigate: (destination: Destination) => void }) {
  const utils = trpc.useUtils();
  const workspace = trpc.nsos.schoolOperator.workspace.useQuery({ schoolId });
  const [refreshConfirmed, setRefreshConfirmed] = useState(false);
  const [profileConfirmed, setProfileConfirmed] = useState(false);
  const [profile, setProfile] = useState({ mission: "", targetLearners: "", brandTone: "", teachingPhilosophy: "", curriculumStrategy: "", pricingApproach: "", policyNotes: "", operatingGoals: "" });
  const refresh = trpc.nsos.schoolOperator.refresh.useMutation({ onSuccess: async insights => { setRefreshConfirmed(false); toast.success(`${insights.length} private School Operator insight${insights.length === 1 ? "" : "s"} refreshed.`); await utils.nsos.schoolOperator.workspace.invalidate({ schoolId }); }, onError: error => toast.error(error.message) });
  const saveProfile = trpc.nsos.schoolOperator.saveProfile.useMutation({ onSuccess: async () => { setProfileConfirmed(false); toast.success("Institution operating memory saved for future private planning."); await utils.nsos.schoolOperator.workspace.invalidate({ schoolId }); }, onError: error => toast.error(error.message) });
  const dismiss = trpc.nsos.schoolOperator.dismissInsight.useMutation({ onSuccess: async () => { toast.success("Insight dismissed for this institution."); await utils.nsos.schoolOperator.workspace.invalidate({ schoolId }); }, onError: error => toast.error(error.message) });
  const data = workspace.data;
  const pending = refresh.isPending || saveProfile.isPending || dismiss.isPending;

  useEffect(() => {
    const source = data?.profile;
    if (!source) return;
    setProfile({ mission: source.mission ?? "", targetLearners: source.targetLearners ?? "", brandTone: source.brandTone ?? "", teachingPhilosophy: source.teachingPhilosophy ?? "", curriculumStrategy: source.curriculumStrategy ?? "", pricingApproach: source.pricingApproach ?? "", policyNotes: source.policyNotes ?? "", operatingGoals: source.operatingGoals ?? "" });
  }, [data?.profile?.updatedAt]);

  if (workspace.isLoading) return <div className="grid min-h-80 place-items-center rounded-[1.5rem] border border-[#dce8e0] bg-white"><Loader2 className="h-6 w-6 animate-spin text-[#087158] motion-reduce:animate-none" /></div>;
  if (!data) return <div className="rounded-[1.5rem] border border-[#efd2cb] bg-[#fff7f5] p-6 text-sm text-[#84463d]">School Operator data is unavailable. Refresh the page and try again.</div>;
  const metrics = [
    { label: "Active students", value: data.dashboard.activeStudents, icon: Activity },
    { label: "Pending admissions", value: data.dashboard.pendingAdmissions, icon: ClipboardCheck },
    { label: "Attendance rate", value: `${data.dashboard.attendanceRate}%`, icon: BrainCircuit },
    { label: "Outstanding", value: new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(data.dashboard.outstanding), icon: WalletCards },
  ];
  const emailReadiness = data.commandCenter.communications.email;
  const health = emailReadiness.failedCount > 0 ? { label: "Needs review", detail: `${emailReadiness.failedCount} recorded email delivery failure${emailReadiness.failedCount === 1 ? "" : "s"}. NSOS will not retry or change delivery settings automatically.`, className: "border-[#efc6be] bg-[#fff5f2] text-[#8d4137]" } : emailReadiness.managedSenderNeedsVerification ? { label: "Attention required", detail: "Email sender verification is still required before the institution should rely on managed delivery.", className: "border-[#ead9a6] bg-[#fffaf0] text-[#785f2c]" } : { label: "No recorded delivery failure", detail: "This reflects current NSOS delivery records only; it is not a guarantee that every external service is healthy.", className: "border-[#c7e4d1] bg-[#f2fbf5] text-[#216044]" };
  return <div className="grid gap-6">
    <section className="overflow-hidden rounded-[1.6rem] border border-[#9bd4bb] bg-[radial-gradient(circle_at_94%_6%,rgba(191,255,217,.25),transparent_30%),linear-gradient(135deg,#062d28_0%,#075e4c_60%,#0a8062_100%)] p-5 text-white shadow-[0_20px_50px_rgba(5,67,52,.15)] sm:p-7"><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><div className="flex items-center gap-2"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#d8fae8] text-[#075541]"><BrainCircuit className="h-5 w-5" /></span><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#c9f0dc]">AI School Operator</p></div><h2 className="mt-4 text-3xl font-black tracking-[-.045em] sm:text-4xl">What needs your attention?</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#cce9da]">NSOS turns current, tenant-scoped operational data into explainable private recommendations. It never predicts individual outcomes, sends messages, changes records, or runs a consequential action without the right protected workflow and your approval.</p></div><div className="rounded-2xl border border-white/15 bg-black/10 p-4 text-xs leading-5 text-[#e6faef]"><div className="flex items-center gap-2 font-extrabold"><ShieldCheck className="h-4 w-4" />Approval-first intelligence</div><p className="mt-2 text-white/75">Refresh reads current aggregate data only. Every recommendation is a handoff; no grades, certificates, prices, people, payments, provider changes, messages, domains, or public content are changed here.</p></div></div><label className="mt-5 flex gap-2 rounded-xl border border-white/15 bg-black/10 p-3 text-[11px] font-semibold leading-4 text-white/90"><input type="checkbox" checked={refreshConfirmed} onChange={event => setRefreshConfirmed(event.target.checked)} className="mt-0.5 h-4 w-4 accent-[#d8fae8]" />I understand this refresh creates or updates private, explainable insight records only. It does not take action.</label><button type="button" disabled={!refreshConfirmed || pending} onClick={() => refresh.mutate({ schoolId, confirmed: true })} className="mt-3 inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-white px-4 text-xs font-extrabold text-[#075541] disabled:cursor-not-allowed disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${refresh.isPending ? "animate-spin motion-reduce:animate-none" : ""}`} />Refresh private insights</button></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(metric => <div key={metric.label} className="rounded-2xl border border-[#dce9e1] bg-white p-4 shadow-[0_8px_20px_rgba(20,58,42,.04)]"><metric.icon className="h-4 w-4 text-[#167457]" /><p className="mt-3 text-2xl font-black tracking-[-.04em] text-[#244b39]">{metric.value}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.08em] text-[#718279]">{metric.label}</p></div>)}</section>
    <section className={`rounded-2xl border p-4 ${health.className}`}><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0" /><div><p className="text-xs font-extrabold">System health: {health.label}</p><p className="mt-1 text-[11px] leading-5 opacity-90">{health.detail}</p><button type="button" onClick={() => onNavigate("communications")} className="mt-2 inline-flex items-center gap-1.5 text-[10px] font-extrabold underline-offset-2 hover:underline">Review delivery configuration <ArrowRight className="h-3.5 w-3.5" /></button></div></div></section>
    <section className="rounded-[1.4rem] border border-[#dce9e1] bg-white p-5 shadow-[0_10px_28px_rgba(25,58,42,.05)]"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-base font-extrabold text-[#284c3d]">Private recommendations</p><p className="mt-1 max-w-2xl text-[11px] leading-5 text-[#6b8075]">Each recommendation states its current evidence source and opens a protected workspace. A missing insight is not proof that a problem does not exist; NSOS does not invent trends or individual risk labels.</p></div><span className="rounded-full bg-[#edf8f1] px-3 py-1 text-[10px] font-extrabold text-[#1f704f]">{data.insights.filter((item: any) => item.status === "open").length} open</span></div><div className="mt-4 grid gap-3">{data.insights.filter((item: any) => item.status === "open").map((insight: any) => <article key={insight.id} className={`rounded-xl border p-4 ${tone[insight.severity] ?? tone.info}`}><div className="flex gap-3"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-xs font-extrabold">{insight.title}</p><p className="mt-1 text-[11px] leading-5 opacity-90">{insight.detail}</p></div><button type="button" disabled={pending} onClick={() => dismiss.mutate({ schoolId, insightId: insight.id, confirmed: true })} className="rounded-lg bg-white/70 p-1.5 transition hover:bg-white" aria-label={`Dismiss ${insight.title}`}><X className="h-3.5 w-3.5" /></button></div><p className="mt-3 text-[10px] font-semibold opacity-80">Evidence: {insight.evidence.metric.replaceAll("_", " ")} · {insight.evidence.value} · {insight.evidence.source}</p>{insight.actionDestination && <button type="button" onClick={() => onNavigate(insight.actionDestination as Destination)} className="mt-3 inline-flex items-center gap-1.5 text-[10px] font-extrabold underline-offset-2 hover:underline">Review in the protected workspace <ArrowRight className="h-3.5 w-3.5" /></button>}</div></div></article>)}{!data.insights.some((item: any) => item.status === "open") && <p className="rounded-xl border border-dashed border-[#d9e7de] bg-[#fbfdfb] p-5 text-xs leading-5 text-[#6d8277]">No refreshed insights yet. Use the explicit refresh above to assess the current tenant-scoped operational state. It will not change any institution record.</p>}</div></section>
    <section className="rounded-[1.4rem] border border-[#dce9e1] bg-white p-5 shadow-[0_10px_28px_rgba(25,58,42,.04)]"><div><p className="text-base font-extrabold text-[#284c3d]">Institution operating memory</p><p className="mt-1 max-w-2xl text-[11px] leading-5 text-[#6b8075]">Save the owner-approved context that future private planning should respect. Do not enter passwords, provider keys, banking details, learner records, staff identities, or sensitive personal information.</p></div><div className="mt-4 grid gap-3 md:grid-cols-2"><Field label="Mission" value={profile.mission} onChange={mission => setProfile(value => ({ ...value, mission }))} /><Field label="Intended learners" value={profile.targetLearners} onChange={targetLearners => setProfile(value => ({ ...value, targetLearners }))} /><Field label="Brand tone" value={profile.brandTone} onChange={brandTone => setProfile(value => ({ ...value, brandTone }))} /><Field label="Teaching philosophy" value={profile.teachingPhilosophy} onChange={teachingPhilosophy => setProfile(value => ({ ...value, teachingPhilosophy }))} multiline /><Field label="Curriculum strategy" value={profile.curriculumStrategy} onChange={curriculumStrategy => setProfile(value => ({ ...value, curriculumStrategy }))} multiline /><Field label="Pricing approach" value={profile.pricingApproach} onChange={pricingApproach => setProfile(value => ({ ...value, pricingApproach }))} multiline /><Field label="Policy notes" value={profile.policyNotes} onChange={policyNotes => setProfile(value => ({ ...value, policyNotes }))} multiline /><Field label="Operating goals" value={profile.operatingGoals} onChange={operatingGoals => setProfile(value => ({ ...value, operatingGoals }))} multiline /></div><label className="mt-4 flex gap-2 rounded-xl border border-[#ead9a6] bg-[#fffaf0] p-3 text-[10px] font-semibold leading-4 text-[#745b2b]"><input type="checkbox" checked={profileConfirmed} onChange={event => setProfileConfirmed(event.target.checked)} className="mt-0.5 h-4 w-4 accent-[#087158]" />I confirm this is institution-approved planning context. Saving it does not publish, message, enrol, change finance, grade, issue credentials, or make public claims.</label><button type="button" disabled={!profileConfirmed || pending} onClick={() => saveProfile.mutate({ schoolId, profile, confirmed: true })} className="mt-3 inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#087158] px-4 text-xs font-extrabold text-white disabled:cursor-not-allowed disabled:opacity-50"><ShieldCheck className="h-4 w-4" />Save private operating memory</button></section>
    <section className="rounded-xl border border-[#dce9e1] bg-[#f7fcf8] p-4 text-[10px] leading-5 text-[#587165]"><p className="font-extrabold text-[#315946]">Current limits</p><ul className="mt-2 grid gap-1.5">{data.limitations.map((limit: string) => <li key={limit}>• {limit}</li>)}</ul></section>
  </div>;
}

function Field({ label, value, onChange, multiline = false }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean }) { return <label className="grid gap-1.5 text-[10px] font-extrabold text-[#52695d]"><span>{label}</span>{multiline ? <textarea value={value} onChange={event => onChange(event.target.value)} maxLength={1600} className="min-h-24 rounded-xl border border-[#d9e7df] bg-[#fbfdfb] px-3 py-2 text-xs font-normal leading-5 text-[#244236] outline-none transition focus:border-[#087158] focus:ring-2 focus:ring-[#087158]/10" /> : <input value={value} onChange={event => onChange(event.target.value)} maxLength={180} className="min-h-10 rounded-xl border border-[#d9e7df] bg-[#fbfdfb] px-3 text-xs font-normal text-[#244236] outline-none transition focus:border-[#087158] focus:ring-2 focus:ring-[#087158]/10" />}</label>; }
