import { AlertCircle, BadgeCheck, CircleDollarSign, Loader2, ReceiptText } from "lucide-react";
import { trpc } from "@/lib/trpc";

const formatMoney = (value: string | number) => new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(Number(value));

export function SubscriptionStatusCard({ schoolId }: { schoolId: number }) {
  const subscription = trpc.nsos.platformRevenue.schoolSubscription.useQuery({ schoolId });
  if (subscription.isLoading) return <section className="rounded-[1.2rem] border border-[#e0e5df] bg-white p-5 shadow-[0_10px_32px_rgba(16,45,35,0.035)]"><div className="flex min-h-24 items-center justify-center"><Loader2 className="h-4 w-4 animate-spin text-[#0f5c4f]" /></div></section>;
  if (subscription.error) return <section className="rounded-[1.2rem] border border-[#edd4d1] bg-[#fffafa] p-5 shadow-[0_10px_32px_rgba(126,44,38,0.04)]"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#f7e8e6] text-[#a13e38]"><AlertCircle className="h-4 w-4" /></span><div><p className="text-sm font-semibold text-[#7f302c]">Subscription status is temporarily unavailable</p><p className="mt-1 text-xs leading-5 text-[#8d625e]">NSOS could not load this school’s platform billing state. Please refresh the page or contact the NSOS operator if the issue continues.</p></div></div></section>;
  const data = subscription.data;
  const state = data?.subscription?.status ?? "trial";
  const latest = data?.billingRecords?.[0];
  const tone = state === "active" ? "bg-[#e2f1e8] text-[#176145]" : state === "payment_due" ? "bg-[#f7eed9] text-[#8a5a12]" : state === "suspended" || state === "cancelled" ? "bg-[#f7e8e6] text-[#a13e38]" : "bg-[#e2f0f3] text-[#216574]";

  return <section className="rounded-[1.2rem] border border-[#dfe5df] bg-white shadow-[0_10px_32px_rgba(16,45,35,0.035)]"><div className="flex items-start justify-between gap-4 border-b border-[#e8ece7] px-5 py-4"><div><div className="flex items-center gap-2"><CircleDollarSign className="h-4 w-4 text-[#0f5c4f]" /><p className="text-sm font-semibold text-[#20342c]">Your NSOS subscription</p></div><p className="mt-1 text-xs leading-5 text-[#758079]">Commercial status is visible to school owners and administrators only.</p></div><span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold capitalize ${tone}`}>{state.replace("_", " ")}</span></div><div className="grid gap-4 px-5 py-5 sm:grid-cols-2"><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#87918b]">Plan</p><p className="mt-1 text-sm font-semibold text-[#274237]">{data?.plan?.name ?? "Commercial plan pending"}</p><p className="mt-1 text-xs leading-5 text-[#758079]">{data?.subscription?.billingCycle === "annual" ? "Annual billing cycle" : data?.subscription?.billingCycle === "monthly" ? "Monthly billing cycle" : "Billing schedule will be confirmed by NSOS."}</p></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#87918b]">Latest billing record</p>{latest ? <><p className="mt-1 text-sm font-semibold text-[#274237]">{latest.invoiceNo} · {formatMoney(latest.amount)}</p><p className="mt-1 flex items-center gap-1.5 text-xs text-[#758079]"><ReceiptText className="h-3.5 w-3.5" />{latest.status === "paid" ? "Payment verified" : latest.status === "issued" ? "Payment record issued" : latest.status}</p></> : <p className="mt-1 flex items-center gap-1.5 text-xs leading-5 text-[#758079]"><BadgeCheck className="h-3.5 w-3.5" />No NSOS billing record has been issued.</p>}</div></div></section>;
}
