import { BarChart3, BookOpenCheck, CircleAlert, Loader2, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { trpc } from "@/lib/trpc";

const styleLabel: Record<string, string> = { balanced: "Balanced", step_by_step: "Step-by-step", worked_examples: "Worked example", concise_review: "Concise review" };

export function TeacherAiTutorAnalytics({ schoolId }: { schoolId: number }) {
  const analytics = trpc.nsos.aiTutors.teacherAnalytics.useQuery({ schoolId });
  if (analytics.isLoading) return <div className="grid min-h-[320px] place-items-center rounded-[1.2rem] border border-[#e0e5df] bg-white"><Loader2 className="h-5 w-5 animate-spin text-[#0f5c4f]" /></div>;
  if (analytics.error || !analytics.data) {
    const errorMessage = analytics.error?.message || "Try again shortly.";
    return (
      <div className="rounded-xl border border-rose-200 bg-rose-50 p-6">
        <p className="text-sm font-semibold text-rose-800">Tutor insights unavailable</p>
        <p className="mt-1 text-xs leading-5 text-rose-700">{errorMessage}</p>
      </div>
    );
  }
  const data = analytics.data;
  if (!data.linkedTeacher) return <Empty title="Teacher record not linked" detail="Your teacher account needs an active staff profile before tutor insights can be limited to your assigned subjects and classes. Ask a school administrator to link your staff record." />;
  if (!data.assignments.length) return <Empty title="No class-subject assignments yet" detail="Tutor insights appear after an administrator assigns you to an active class and subject. This protects learners outside your teaching remit." />;
  const styles = Object.entries(data.summary.styles).filter(([, count]) => count > 0);
  return <div className="grid gap-6">
    <section className="rounded-[1.2rem] bg-[#123b31] p-6 text-white sm:p-7"><div className="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-white/50">Teacher tutor insights</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.045em]">See how study support is being presented.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-white/65">Review the explanation formats used for learners in your assigned class subjects. Use this as a conversation starter—not as an automated learner assessment.</p></div><div className="rounded-xl border border-white/10 bg-white/[.08] px-4 py-3 text-xs"><p className="font-semibold">Privacy boundary</p><p className="mt-1 text-white/60">No questions, answers, or feedback notes are displayed here.</p></div></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Sparkles className="h-4 w-4" />} label="Active tutors" value={data.summary.activeTutors} /><Metric icon={<UsersRound className="h-4 w-4" />} label="Eligible learners" value={data.summary.eligibleLearners} /><Metric icon={<BarChart3 className="h-4 w-4" />} label="Adaptation on" value={data.summary.adaptationEnabled} /><Metric icon={<BookOpenCheck className="h-4 w-4" />} label="Rating signals" value={data.summary.feedbackSignals} /></section>
    <section className="rounded-[1.2rem] border border-[#e0e5df] bg-white p-5 shadow-[0_10px_32px_rgba(16,45,35,.035)] sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-[#2d4439]">Explanation formats in your remit</p><p className="mt-1 text-xs leading-5 text-[#758079]">Formats are derived from rating categories only. A learner may turn adaptation off at any time.</p></div><div className="flex flex-wrap gap-2">{styles.length ? styles.map(([style, count]) => <span key={style} className="rounded-full bg-[#edf3ed] px-3 py-1.5 text-[11px] font-bold text-[#176145]">{styleLabel[style]} · {count}</span>) : <span className="text-xs text-[#758079]">No eligible active tutor interactions yet</span>}</div></div></section>
    <section className="overflow-hidden rounded-[1.2rem] border border-[#e0e5df] bg-white shadow-[0_10px_32px_rgba(16,45,35,.035)]"><div className="border-b border-[#e7ebe6] p-5 sm:p-6"><p className="text-sm font-semibold text-[#2d4439]">Tutor coverage by class</p><p className="mt-1 text-xs leading-5 text-[#758079]">Only tutors and class subjects formally assigned to you are included.</p></div>{data.tutorClasses.length ? <div className="grid gap-px bg-[#edf0eb] md:grid-cols-2">{data.tutorClasses.map(item => <article key={`${item.tutorId}:${item.className}`} className="bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-[#30463b]">{item.tutorName}</p><p className="mt-1 text-xs text-[#68776f]">{item.subjectName} · {item.className}</p></div><span className="rounded-full bg-[#e2f1e8] px-2.5 py-1 text-[10px] font-bold text-[#176145]">{item.learners} learner{item.learners === 1 ? "" : "s"}</span></div><div className="mt-4 flex flex-wrap gap-2 text-[11px]">{Object.entries(item.styles).filter(([, count]) => count > 0).map(([style, count]) => <span key={style} className="rounded-md bg-[#f5faf6] px-2.5 py-1.5 font-semibold text-[#456254]">{styleLabel[style]} · {count}</span>)}</div><p className="mt-4 text-[11px] text-[#758079]">{item.adaptationEnabled} adaptation enabled · {item.feedbackSignals} rating signal{item.feedbackSignals === 1 ? "" : "s"}</p></article>)}</div> : <div className="p-7 text-center text-xs leading-5 text-[#758079]">No active AI tutor currently matches your assigned class-subject combinations.</div>}</section>
    <section className="overflow-hidden rounded-[1.2rem] border border-[#e0e5df] bg-white shadow-[0_10px_32px_rgba(16,45,35,.035)]"><div className="border-b border-[#e7ebe6] p-5 sm:p-6"><p className="text-sm font-semibold text-[#2d4439]">Learner adaptation overview</p><p className="mt-1 text-xs leading-5 text-[#758079]">Names are shown only because these learners are in your assigned classes and subjects. Review support needs through normal school processes.</p></div>{data.learners.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#f8faf7] text-[10px] uppercase tracking-[.1em] text-[#758079]"><tr><th className="px-5 py-3 font-semibold">Learner</th><th className="px-5 py-3 font-semibold">Class</th><th className="px-5 py-3 font-semibold">Tutor</th><th className="px-5 py-3 font-semibold">Current format</th><th className="px-5 py-3 font-semibold">Adaptation</th><th className="px-5 py-3 font-semibold">Signals</th></tr></thead><tbody className="divide-y divide-[#edf0eb]">{data.learners.map(item => <tr key={`${item.studentId}:${item.tutorId}`}><td className="px-5 py-3"><p className="text-xs font-semibold text-[#30463b]">{item.learnerName}</p><p className="mt-0.5 text-[11px] text-[#758079]">{item.admissionNo}</p></td><td className="px-5 py-3 text-xs text-[#55685f]">{item.className}</td><td className="px-5 py-3"><p className="text-xs font-semibold text-[#40534a]">{item.tutorName}</p><p className="mt-0.5 text-[11px] text-[#758079]">{item.subjectName}</p></td><td className="px-5 py-3"><span className="rounded-full bg-[#edf3ed] px-2.5 py-1 text-[11px] font-bold text-[#176145]">{styleLabel[item.teachingStyle]}</span></td><td className="px-5 py-3 text-xs"><span className={item.adaptationEnabled ? "font-semibold text-[#257152]" : "font-semibold text-[#8a5a12]"}>{item.adaptationEnabled ? "On" : "Learner chose off"}</span></td><td className="px-5 py-3 text-xs text-[#55685f]">{item.feedbackSignals}</td></tr>)}</tbody></table></div> : <div className="p-7 text-center text-xs leading-5 text-[#758079]">No eligible learners are currently enrolled in your assigned tutor-supported subjects.</div>}</section>
    <section className="rounded-[1.2rem] border border-[#d9e7dc] bg-[#f6fbf7] p-5"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-white text-[#176145]"><ShieldCheck className="h-4 w-4" /></span><div><p className="text-sm font-semibold text-[#29483b]">Interpret with human judgment</p><p className="mt-1 text-xs leading-5 text-[#65746c]">A teaching format is not a diagnosis, score, or decision about a learner. Discuss learning needs with the student and school team, and use normal safeguarding and academic-support pathways where needed.</p></div></div></section>
  </div>;
}

function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="rounded-xl border border-[#e0e5df] bg-white p-4 shadow-[0_8px_20px_rgba(16,45,35,.025)]"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#edf3ed] text-[#176145]">{icon}</span><p className="mt-4 text-2xl font-semibold tracking-[-.04em] text-[#263d32]">{value}</p><p className="mt-1 text-xs text-[#758079]">{label}</p></div>; }
function Empty({ title, detail }: { title: string; detail: string }) { return <div className="rounded-[1.2rem] border border-[#e7d5b2] bg-[#fffaf0] p-7 text-center"><CircleAlert className="mx-auto h-5 w-5 text-[#8a5a12]" /><p className="mt-3 text-sm font-semibold text-[#76521a]">{title}</p><p className="mx-auto mt-2 max-w-lg text-xs leading-5 text-[#8a6a34]">{detail}</p></div>; }
