import { trpc } from "@/lib/trpc";
import { Check, ClipboardCheck, MessageSquarePlus, RotateCcw, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type CommentAnchor = "topic" | "objectives" | "resources";
type ReviewItem = { id: number; weekNo: number; topic: string; objectives?: string | null; resources?: string | null; reviewStatus: "pending_review" | "approved" | "returned" | "published"; reviewNote?: string | null; className: string; subjectName: string; termName: string; comments?: Array<{ id: number; anchor: CommentAnchor; body: string; createdAt: Date }> };

function statusClass(status: ReviewItem["reviewStatus"]) {
  if (status === "published") return "bg-[#e1f1e6] text-[#176145]";
  if (status === "returned") return "bg-[#fff0ec] text-[#a14538]";
  if (status === "approved") return "bg-[#e9f4ec] text-[#277052]";
  return "bg-[#fff6df] text-[#8a5a12]";
}

export function TeacherWeeklyPlanReview({ schoolId, onDone }: { schoolId: number; onDone: () => void }) {
  const reviews = trpc.nsos.academics.teacherSchemeReviews.useQuery({ schoolId });
  const [notes, setNotes] = useState<Record<number, string>>({});
  const [openCommentKey, setOpenCommentKey] = useState<string | null>(null);
  const [commentDrafts, setCommentDrafts] = useState<Record<string, string>>({});
  const review = trpc.nsos.academics.reviewSchemeRow.useMutation({ onSuccess: (_, variables) => { toast.success(variables.decision === "approved" ? "Weekly plan approved. It is ready for school publication." : "Weekly plan returned with your revision note."); reviews.refetch(); onDone(); }, onError: error => toast.error(error.message) });
  const addComment = trpc.nsos.academics.addSchemeRowInlineComment.useMutation({ onSuccess: () => { toast.success("Section comment saved for the school review team."); setOpenCommentKey(null); reviews.refetch(); onDone(); }, onError: error => toast.error(error.message) });
  if (reviews.isLoading) return <section className="rounded-[1.2rem] border border-[#dbe6dd] bg-white p-6"><p className="text-sm font-semibold text-[#345044]">Loading your assigned weekly plans…</p></section>;
  if (reviews.error) return <section className="rounded-[1.2rem] border border-[#eed7d3] bg-[#fffaf9] p-6"><p className="text-sm font-semibold text-[#913d36]">Teacher review desk unavailable</p><p className="mt-1 text-xs text-[#765b57]">{reviews.error.message}</p></section>;
  const items = (reviews.data ?? []) as ReviewItem[];
  const section = (item: ReviewItem, anchor: CommentAnchor, label: string, value: string | null | undefined) => {
    const key = `${item.id}:${anchor}`;
    const sectionComments = (item.comments ?? []).filter(comment => comment.anchor === anchor);
    return <div className="rounded-lg border border-[#e5ece6] bg-white px-3 py-2.5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[0.11em] text-[#718178]">{label}</p><p className="mt-1 text-xs leading-5 text-[#41564b]">{value?.trim() || "No detail supplied in the imported scheme."}</p></div>{item.reviewStatus !== "published" && <button type="button" onClick={() => setOpenCommentKey(openCommentKey === key ? null : key)} className="inline-flex shrink-0 items-center gap-1 rounded-md px-2 py-1 text-[11px] font-bold text-[#176145] hover:bg-[#edf6ef]" aria-expanded={openCommentKey === key}><MessageSquarePlus className="h-3.5 w-3.5" />Comment</button>}</div>{sectionComments.length ? <div className="mt-2 grid gap-1.5 border-t border-[#edf1ed] pt-2">{sectionComments.map(comment => <div key={comment.id} className="rounded-md bg-[#fff9e9] px-2.5 py-2 text-[11px] leading-4 text-[#67531d]"><span className="mr-1 font-bold">Teacher note:</span>{comment.body}</div>)}</div> : null}{openCommentKey === key && <div className="mt-3 border-t border-[#edf1ed] pt-3"><label className="sr-only" htmlFor={`comment-${key}`}>Comment on {label}</label><textarea id={`comment-${key}`} value={commentDrafts[key] ?? ""} onChange={event => setCommentDrafts(current => ({ ...current, [key]: event.target.value }))} maxLength={1200} autoFocus className="min-h-20 w-full rounded-lg border border-[#dce7de] bg-[#fbfcfa] p-2.5 text-xs text-[#31483e] outline-none focus:border-[#0f5c4f] focus:ring-2 focus:ring-[#0f5c4f]/10" placeholder={`Point to a specific improvement in the ${label.toLowerCase()}.`} /><div className="mt-2 flex items-center justify-between gap-2"><span className="text-[10px] text-[#7b8981]">Visible to school owners and administrators before publication.</span><div className="flex gap-2"><button type="button" onClick={() => setOpenCommentKey(null)} className="rounded-md px-2 py-1.5 text-[11px] font-bold text-[#65766d] hover:bg-[#f0f4f0]"><X className="inline h-3.5 w-3.5" /> Cancel</button><button type="button" disabled={addComment.isPending || !(commentDrafts[key] ?? "").trim()} onClick={() => addComment.mutate({ schoolId, rowId: item.id, anchor, body: commentDrafts[key] ?? "" })} className="rounded-md bg-[#0f5c4f] px-2.5 py-1.5 text-[11px] font-bold text-white disabled:opacity-50">{addComment.isPending ? "Saving…" : "Save comment"}</button></div></div></div>}</div>;
  };
  return <section className="rounded-[1.2rem] border border-[#d6e6d9] bg-white p-5 shadow-[0_10px_32px_rgba(16,45,35,0.035)] sm:p-6"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#e6f2e9] text-[#0f5c4f]"><ClipboardCheck className="h-5 w-5" /></span><div><p className="text-sm font-semibold text-[#294238]">Weekly plan approval desk</p><p className="mt-1 text-xs leading-5 text-[#65766d]">Comment directly on the topic, objectives, or resources to make revision feedback precise. School management can read those notes before publication.</p></div></div>{items.length ? <div className="mt-5 grid gap-3">{items.map(item => <div key={item.id} className="rounded-xl border border-[#e1eae2] bg-[#fbfcfa] p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><p className="text-xs font-bold uppercase tracking-[0.1em] text-[#6b7c72]">{item.className} · {item.subjectName} · {item.termName} · Week {item.weekNo}</p><span className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-bold ${statusClass(item.reviewStatus)}`}>{item.reviewStatus.replace("_", " ")}</span></div><div className="mt-3 grid gap-2">{section(item, "topic", "Topic", item.topic)}{section(item, "objectives", "Objectives", item.objectives)}{section(item, "resources", "Resources", item.resources)}</div>{item.reviewStatus !== "published" && <div className="mt-3"><textarea className="min-h-20 w-full rounded-lg border border-[#dfe6e0] bg-white p-3 text-xs text-[#31483e] outline-none focus:border-[#0f5c4f] focus:ring-2 focus:ring-[#0f5c4f]/10" value={notes[item.id] ?? item.reviewNote ?? ""} onChange={event => setNotes(current => ({ ...current, [item.id]: event.target.value }))} placeholder="Optional overall approval note; required when returning for revision." /><div className="mt-2 flex flex-wrap gap-2"><button disabled={review.isPending} onClick={() => review.mutate({ schoolId, rowId: item.id, decision: "approved", reviewNote: notes[item.id] })} className="inline-flex items-center gap-1.5 rounded-lg bg-[#0f5c4f] px-3 py-2 text-xs font-bold text-white disabled:opacity-50"><Check className="h-3.5 w-3.5" />Approve weekly plan</button><button disabled={review.isPending || !(notes[item.id] ?? item.reviewNote ?? "").trim()} onClick={() => review.mutate({ schoolId, rowId: item.id, decision: "returned", reviewNote: notes[item.id] })} className="inline-flex items-center gap-1.5 rounded-lg border border-[#efcfca] bg-white px-3 py-2 text-xs font-bold text-[#a13e38] disabled:opacity-50"><RotateCcw className="h-3.5 w-3.5" />Return for revision</button></div></div>}</div>)}</div> : <div className="mt-5 rounded-xl border border-dashed border-[#d7e1d8] bg-[#fafcf9] p-4 text-xs leading-5 text-[#687970]">No weekly plans are currently assigned to your staff profile. An administrator must assign you to a class-subject before importing an approved scheme for review.</div>}</section>;
}
