import { trpc } from "@/lib/trpc";
import { CheckCircle2, Copy, ExternalLink, Globe2, Loader2, ShieldCheck } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const inputClass = "h-10 w-full rounded-lg border border-[#dfe5df] bg-[#fbfcfa] px-3 text-sm text-[#15201c] outline-none transition focus:border-[#0f5c4f] focus:ring-2 focus:ring-[#0f5c4f]/10";

type WebsiteForm = { headline: string; introduction: string; primaryColor: string; contactEmail: string; contactPhone: string; campusLocation: string; customDomain: string; admissionsEnabled: boolean; published: boolean };

export function WebsiteStudio({ schoolId }: { schoolId: number }) {
  const config = trpc.nsos.website.config.useQuery({ schoolId });
  const [form, setForm] = useState<WebsiteForm>({ headline: "", introduction: "", primaryColor: "#0f5c4f", contactEmail: "", contactPhone: "", campusLocation: "", customDomain: "", admissionsEnabled: true, published: false });
  useEffect(() => {
    if (!config.data?.website) return;
    const site = config.data.website;
    setForm({ headline: site.headline ?? "", introduction: site.introduction ?? "", primaryColor: site.primaryColor ?? "#0f5c4f", contactEmail: site.contactEmail ?? "", contactPhone: site.contactPhone ?? "", campusLocation: site.campusLocation ?? "", customDomain: site.customDomain ?? "", admissionsEnabled: site.admissionsEnabled, published: site.published });
  }, [config.data]);
  const save = trpc.nsos.website.save.useMutation({ onSuccess: () => { toast.success("Website configuration saved."); config.refetch(); }, onError: error => toast.error(error.message) });
  const verify = trpc.nsos.website.verifyDomain.useMutation({ onSuccess: () => { toast.success("Domain verified and activated."); config.refetch(); }, onError: error => toast.error(error.message) });
  const publicPath = useMemo(() => config.data ? `${window.location.origin}/school/${config.data.school.shortCode}` : "", [config.data]);
  if (config.isLoading) return <section className="grid min-h-[320px] place-items-center rounded-[1.2rem] border border-[#e0e5df] bg-white"><Loader2 className="h-5 w-5 animate-spin text-[#0f5c4f]" /></section>;
  if (!config.data) return null;
  const site = config.data.website;
  const submit = (event: FormEvent) => { event.preventDefault(); save.mutate({ schoolId, ...form, headline: form.headline || undefined, introduction: form.introduction || undefined, contactEmail: form.contactEmail || undefined, contactPhone: form.contactPhone || undefined, campusLocation: form.campusLocation || undefined, customDomain: form.customDomain || undefined }); };
  const copy = async (text: string, message: string) => { await navigator.clipboard.writeText(text); toast.success(message); };
  const expectedRecord = site.domainVerificationToken ? `nsos-site-verification=${site.domainVerificationToken}` : "Save a custom domain to generate a verification record.";
  return <div className="grid gap-6">
    <div className="flex flex-col gap-4 rounded-[1.2rem] bg-[#123b31] p-6 text-white sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-white/50">School website</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em]">Publish the school beyond the office.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65">Give your school a branded public home with a clear admissions route and a verifiable custom-domain path.</p></div><div className="rounded-xl bg-white/10 px-4 py-3 text-xs"><p className="font-semibold">{site.published ? "Website published" : "Website in draft"}</p><p className="mt-1 text-white/60">{site.admissionsEnabled ? "Admissions access is enabled" : "Admissions access is off"}</p></div></div>
    <div className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]">
      <form onSubmit={submit} className="rounded-[1.2rem] border border-[#e0e5df] bg-white p-5 shadow-[0_10px_32px_rgba(16,45,35,.035)] sm:p-6"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf3ed] text-[#0f5c4f]"><Globe2 className="h-4 w-4" /></span><div><p className="text-sm font-semibold text-[#2d4439]">Brand & publishing</p><p className="mt-1 text-xs text-[#758079]">Schools control this content themselves. NSOS does not publish learners, families, or staff data.</p></div></div><div className="mt-5 grid gap-4"><Field label="Website headline"><input className={inputClass} value={form.headline} onChange={event => setForm({ ...form, headline: event.target.value })} placeholder={`${config.data.school.name}: learning for a brighter future.`} /></Field><Field label="Introduction"><textarea className={`${inputClass} h-28 py-2`} value={form.introduction} onChange={event => setForm({ ...form, introduction: event.target.value })} placeholder="A short introduction to the school, its values, and its community." /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Contact email"><input type="email" className={inputClass} value={form.contactEmail} onChange={event => setForm({ ...form, contactEmail: event.target.value })} placeholder="admissions@school.edu.ng" /></Field><Field label="Contact phone"><input className={inputClass} value={form.contactPhone} onChange={event => setForm({ ...form, contactPhone: event.target.value })} placeholder="0800 000 0000" /></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Campus location"><input className={inputClass} value={form.campusLocation} onChange={event => setForm({ ...form, campusLocation: event.target.value })} placeholder="Abeokuta, Ogun State" /></Field><Field label="Brand colour"><div className="flex gap-2"><input type="color" className="h-10 w-12 rounded-lg border border-[#dfe5df] bg-[#fbfcfa] p-1" value={form.primaryColor} onChange={event => setForm({ ...form, primaryColor: event.target.value })} /><input className={inputClass} value={form.primaryColor} onChange={event => setForm({ ...form, primaryColor: event.target.value })} /></div></Field></div><div className="grid gap-3 rounded-xl bg-[#f8faf7] p-4 sm:grid-cols-2"><Toggle label="Show admissions button" checked={form.admissionsEnabled} onChange={value => setForm({ ...form, admissionsEnabled: value })} /><Toggle label="Publish website" checked={form.published} onChange={value => setForm({ ...form, published: value })} /></div><button disabled={save.isPending} className="w-fit rounded-xl bg-[#0f5c4f] px-5 py-2.5 text-sm font-bold text-white disabled:opacity-60">{save.isPending ? "Saving…" : "Save website settings"}</button></div></form>
      <aside className="grid content-start gap-5"><section className="rounded-[1.2rem] border border-[#e0e5df] bg-white p-5 shadow-[0_10px_32px_rgba(16,45,35,.035)]"><p className="text-sm font-semibold text-[#2d4439]">School public link</p><p className="mt-2 break-all rounded-lg bg-[#f1f4f0] p-3 font-mono text-[11px] text-[#406056]">{publicPath}</p><div className="mt-3 flex gap-2"><button type="button" onClick={() => void copy(publicPath, "Public school link copied.")} className="rounded-lg border border-[#d8e2d9] bg-[#f6faf6] px-3 py-2 text-xs font-bold text-[#0f5c4f]"><Copy className="mr-1.5 inline h-3.5 w-3.5" />Copy link</button>{site.published && <a href={`/school/${config.data.school.shortCode}`} target="_blank" rel="noreferrer" className="rounded-lg bg-[#123b31] px-3 py-2 text-xs font-bold text-white"><ExternalLink className="mr-1.5 inline h-3.5 w-3.5" />Preview</a>}</div></section>
        <section className="rounded-[1.2rem] border border-[#e0e5df] bg-white p-5 shadow-[0_10px_32px_rgba(16,45,35,.035)]"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#f7eed9] text-[#8a5a12]"><ShieldCheck className="h-4 w-4" /></span><div><p className="text-sm font-semibold text-[#2d4439]">Custom domain</p><p className="mt-1 text-xs leading-5 text-[#758079]">Enter and save the school’s domain. Then add the requested DNS TXT record, connect the domain to this NSOS deployment in platform domain settings, and verify.</p></div></div><Field label="Requested custom domain"><input className={`${inputClass} mt-4`} value={form.customDomain} onChange={event => setForm({ ...form, customDomain: event.target.value.replace(/^https?:\/\//, "") })} placeholder="www.yourschool.edu.ng" /></Field>{site.customDomain && <div className="mt-4 rounded-xl bg-[#f8faf7] p-3"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#7a847e]">DNS ownership record</p><p className="mt-2 font-mono text-[11px] text-[#37564b]">Host: _nsos-verify.{site.customDomain}</p><p className="mt-1 break-all font-mono text-[11px] text-[#37564b]">Value: {expectedRecord}</p><button type="button" onClick={() => void copy(expectedRecord, "DNS verification value copied.")} className="mt-3 text-xs font-bold text-[#0f5c4f]"><Copy className="mr-1 inline h-3.5 w-3.5" />Copy verification value</button></div>}<div className="mt-4 flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs"><CheckCircle2 className={`h-4 w-4 ${site.domainStatus === "active" ? "text-[#176145]" : "text-[#b47a1d]"}`} /><span className="capitalize text-[#536159]">{site.domainStatus.replace("_", " ")}</span></div><button type="button" disabled={!site.customDomain || verify.isPending} onClick={() => verify.mutate({ schoolId })} className="rounded-lg bg-[#123b31] px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{verify.isPending ? "Checking…" : "Verify domain"}</button></div></section></aside>
    </div>
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-xs font-semibold text-[#43534c]"><span>{label}</span>{children}</label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex cursor-pointer items-center justify-between gap-3 text-xs font-semibold text-[#43534c]"><span>{label}</span><input type="checkbox" className="h-4 w-4 accent-[#0f5c4f]" checked={checked} onChange={event => onChange(event.target.checked)} /></label>; }
